import { createContext, useContext, useState, useEffect } from 'react';

const translations = {
  en: {
    nav_home: 'Home',
    nav_shop: 'Shop',
    nav_about: 'About',
    nav_contact: 'Contact',
    search_placeholder: 'Search plants...',
    cart: 'Cart',
    login: 'Login',
    signup: 'Sign Up',
    logout: 'Logout',
    dashboard: 'Dashboard',
    continue_shopping: 'Continue Shopping',
    need_help: 'Need help?',
    whatsapp_support: 'Chat on WhatsApp for care support — free lifetime!',
    chat_now: 'Chat now',
    hello: 'Hello',
    green_family: "Here's what's happening with your green family.",
    total_orders: 'Total Orders',
    pending: 'Pending',
    delivered: 'Delivered',
    wishlist: 'Wishlist',
    wallet: 'Wallet • Loyalty',
    loved_by_plants: 'Loved by plants',
    view_rewards: 'View rewards',
    recent_orders: 'Recent Orders',
    care_reminders: 'Care Reminders',
    refer_earn: 'Refer & Earn',
    landscaping_title: 'Any type of landscaping & gardening plants all over Kerala.',
    landscaping_desc: 'Any type of landscaping, gardening plants will be providing in all over Kerala — from Pezhummoodu, Thiruvananthapuram to Kasaragod.',
    cancel_reason_required: 'Cancel reason is mandatory',
    cancel_reason_placeholder: 'e.g., Ordered by mistake, delivery too late...',
    keep_order: 'Keep order',
    confirm_cancel: 'Confirm cancel',
    kerala_coverage: 'Kerala-wide Service • 14 Districts',
    hero_badge: 'New Season Collection Live — Up to 30% OFF',
    hero_title1: 'PLANTS THAT',
    hero_title2: 'Make You',
    hero_title3: 'BREATHE BETTER',
    hero_desc: 'Curated, organic & nursery-fresh plants delivered to your doorstep. From low-light heroes to pet-friendly picks — find your perfect green companion.',
    shop_collection: 'Shop Collection →',
    how_we_grow: 'How we grow',
    best_sellers: 'Best sellers this week',
    best_sellers_sub: 'sellers',
    filter: 'Filter:',
    popular: 'Popular',
    new_in: 'New In',
    sale: 'Sale',
    view_all_plants: 'View All Plants',
    why_love_us: 'Why 12k+ love us',
    not_just_plant: 'Not just a plant.',
    healthy_start: 'A healthy start.',
    delivery_address: 'Delivery Address',
    fetched_from_profile: 'fetched from profile',
    saved_addresses: 'Saved addresses — tap to fill',
    use_current_location: 'Use Current Location',
    street_house: 'Street, House No.',
    city: 'City',
    state: 'State',
    postal_code: 'Postal Code',
    country: 'Country',
    phone_owner: 'Phone (for owner contact)',
    delivery_note: 'Delivery Note (optional)',
    payment_method: 'Payment Method',
    online_removed: 'Online payment removed — pay when you receive the plants. Owner will confirm before dispatch.',
    cash_on_delivery: 'Cash on Delivery (COD)',
    recommended: 'RECOMMENDED',
    pay_after: 'Pay after delivery — cash / UPI to delivery person. No advance. Owner will call to confirm address & shipping extra (₹39-79 for potted).',
    how_it_works: 'How it works:',
    order_summary: 'Order Summary',
    subtotal: 'Subtotal',
    shipping: 'Shipping',
    total: 'Total',
    place_order: 'Place Order — COD →',
    contact_help: 'Hi! Need help choosing a low-light plant for your bedroom? I can suggest 3 pet-safe options 🌿',
    send_message: 'Send a message',
    your_name: 'Your Name',
    email: 'Email',
    subject: 'Subject',
    message: 'Message',
    send: 'Send Message →',
    visit_greenhouse: 'Visit our greenhouse',
    find_us_map: 'Find us on map',
    // Landing extended
    landing_best_title: 'Best sellers this week',
    landing_sale_badge: 'SALE',
    landing_variants_fixed: 'variants • Fixed',
    landing_stock_left: 'left',
    landing_stock_label: 'Stock:',
    landing_options: 'options',
    landing_fixed: 'Fixed',
    landing_with_pot: 'With Plastic Pot • Fixed',
    landing_add_to_cart: 'Add to Cart',
    landing_loading: 'Loading best sellers...',
    landing_landscaping_desc2: 'From Pezhummoodu, Thiruvananthapuram to Kasaragod — we supply any landscaping, rooftop, balcony, indoor & outdoor gardening plants. Direct from our 2-acre nursery, with on-site landscaping team, 3-5 day delivery, GST bill & after-care support.',
    landing_residential: '✓ Residential villas',
    landing_offices: '✓ Offices & Hotels',
    landing_schools: '✓ Schools & Resorts',
    landing_nurseries: '✓ Nurseries & Projects',
    landing_districts1: 'TVM • Kollam • Pathanamthitta • Alappuzha',
    landing_districts2: 'Kottayam • Idukki • Ernakulam • Thrissur',
    landing_districts3: 'Palakkad • Malappuram • Kozhikode • Wayanad • Kannur • Kasaragod',
    landing_get_quote: 'Get Landscaping Quote →',
    landing_browse_plants: 'Browse Plants',
    landing_base_location: 'Base: H34Q+9FP, Pezhummoodu, Thiruvananthapuram, Kerala 695575 • Pan-Kerala delivery • Installation team available',
    landing_garden_title: 'Garden Landscaping',
    landing_garden_desc: 'Lawn, hedges, palms, flowering',
    landing_balcony_title: 'Balcony & Terrace',
    landing_balcony_desc: 'Indoor air-purifying picks',
    landing_office_title: 'Office / Resort',
    landing_office_desc: 'Areca, Lucky Bamboo, Calathea',
    landing_all_kerala: 'All Kerala',
    landing_all_kerala_desc: 'Any plant, any quantity — delivered & installed. 14 districts, 3-5 days.',
    landing_pezhummoodu: 'Pezhummoodu → Everywhere',
    landing_nursery_fresh_title: 'Nursery-fresh in 48 hrs',
    landing_nursery_fresh_desc: 'Picked, packed & shipped from our Pezhummoodu, Thiruvananthapuram, Kerala greenhouse with zero middlemen.',
    landing_organic_title: 'Organic & Safe',
    landing_organic_desc: 'No harmful pesticides. Pet & kid friendly options.',
    landing_expert_title: 'Expert Care Support',
    landing_expert_desc: 'Free WhatsApp help from horticulturists for lifetime.',
    landing_safe_title: 'Safe Arrival Guarantee',
    landing_safe_desc: 'Crush-proof, breathable packaging. Replacement if harmed.',
    landing_eco_title: 'Eco Packaging',
    landing_eco_desc: 'Plastic-free, biodegradable pots & recycled boxes.',
    landing_our_story: 'Our Story',
    landing_reviews_rating: '★ 4.9/5 from 3,421 reviews',
    landing_direct_badge: 'Direct from our greenhouse',
    landing_grown_title1: 'Grown with care.',
    landing_grown_title2: 'Delivered with love.',
    landing_grown_desc: 'No middlemen. No market markup. From our 2-acre organic nursery in Pezhummoodu, Thiruvananthapuram, Kerala to your doorstep in 3 days. Every plant is hand-picked, health-checked, and packed live — not warehoused.',
    curated_badge: 'Fresh from our 2-acre nursery',
    curated_title1: 'Grown with care.',
    curated_title2: 'Styled for your space.',
    curated_desc: 'Hand-picked, health-checked and live-packed in Pezhummoodu. Rooftop to living room — we curate the right green for your light, space and lifestyle.',
    curated_feature_badge: 'Living Installations',
    curated_feature_title: 'Garden & landscape design, done for you',
    curated_feature_desc: 'Lawn, hedges, palms, flowering borders — our on-site team designs, plants and hands over a ready garden in 2–3 visits.',
    curated_feature_cta1: 'Get free visit →',
    curated_feature_cta2: 'Shop plants',
    curated_balcony_label: 'Balcony & Terrace',
    curated_balcony_title: 'Small space, big green',
    curated_balcony_desc: 'Air-purifying picks for low light, wind and sun.',
    curated_office_label: 'Offices & Hotels',
    curated_office_title: 'Calm, premium, low-maintenance',
    curated_office_desc: 'Areca, Calathea, Lucky Bamboo — statement plants.',
    curated_stat_homes: 'Homes greened',
    curated_stat_rating: 'reviews',
    curated_stat_eta: 'Nursery → doorstep',
    curated_stat_nursery: 'organic nursery',
    curated_footer_note: 'GST bill • 3–5 day delivery • Installation team on request',
    landing_stat_48h: '48h',
    landing_stat_48h_label: 'Nursery to doorstep',
    landing_stat_damage: '0.8%',
    landing_stat_damage_label: 'Damage rate',
    landing_stat_replace: '14d',
    landing_stat_replace_label: 'Replace guarantee',
    landing_meet_growers: 'Meet the growers →',
    landing_shop_live: 'Shop live plants',
    landing_handpicked_title: 'Hand-picked',
    landing_handpicked_desc: 'Health score 9/10. Only the best leaves ship.',
    landing_livepacked_title: 'Live-packed',
    landing_livepacked_desc: 'Breathable tube, coco-peat, anti-crush.',
    landing_qr_title: 'QR Care',
    landing_qr_desc: 'Scan for watering, light, pet-safe guide.',
    landing_lifetime_title: 'Lifetime help',
    landing_lifetime_desc: 'WhatsApp our growers — free forever.',
    landing_quote: '“Plants arrived like they were still in the nursery”',
    landing_quote_author: '— Priya S., Mumbai • 12 orders',
    landing_newsletter_badge: 'Join the club',
    landing_newsletter_title1: 'Get 10% off + free',
    landing_newsletter_title2: 'care guide PDF',
    landing_newsletter_desc: 'No spam. Unsubscribe anytime. 12,000+ plant parents already inside.',
    landing_your_email: 'Your email',
    landing_join: 'Join →',
    // About
    about_badge: 'About GreenNest • Est 2022 Pezhummoodu, TVM',
    about_hero_title1: 'We grow happiness,',
    about_hero_title2: 'one plant at a time.',
    about_hero_desc: 'Since 2022, from a 200 sq ft nursery in Kothrud to 12,000+ homes across India — our young journey is rooted in organic care, honest pricing and lifetime plant parent support.',
    about_shop_plants: 'Shop Plants →',
    about_our_story: 'Our Story',
    about_stats_plants: 'Plants delivered',
    about_stats_reviews: '3,421 reviews',
    about_stats_families: 'Happy families',
    about_organic_title: 'Organic since day one',
    about_organic_desc: 'No pesticides • Eco pots • Carbon-neutral delivery',
    about_story_label: 'Our Story',
    about_story_title1: 'From a seed of an idea',
    about_story_title2: 'to a forest of homes.',
    about_story_p1: '2022 — Small start. Founder Asha Patel, a botany graduate, started with 80 mother plants in her balcony, selling at Pezhummoodu, TVM farmers’ markets. The promise: “Healthy, hand-picked plants delivered with care.”',
    about_story_p2: '2023 — The greenhouse. A 2-acre organic greenhouse in Mulshi, zero-chemical soil, rain-water harvesting and our first team of 5 women growers. We introduced crush-proof tubes — damage rate dropped from 12% to 0.8%.',
    about_story_p3: '2024 — Digital bloom. Launched GreenNest.in with care videos, WhatsApp support and QR care cards that made plant parenting easy for first-timers.',
    about_story_p4: 'Today — 2026. 50k+ plants delivered, 12k+ families, 4.9★ rating in just 4 years. Still family-run, still organic, still obsessed with that new-leaf joy — and growing faster than ever.',
    about_year_2022: '80 plants, 1 balcony',
    about_year_2026: '2 acres, 50k+ plants • 4 years',
    about_promise: 'Our promise: Healthy, organic plants + lifetime care support.',
    about_timeline1_title: 'Idea Sown',
    about_timeline1_desc: 'Balcony nursery, farmers’ market debut',
    about_timeline2_title: 'Greenhouse',
    about_timeline2_desc: 'Mulshi organic farm, tube packaging',
    about_timeline3_title: 'Online Store',
    about_timeline3_desc: 'Pan-India delivery, QR care guides',
    about_timeline4_title: '12k Families',
    about_timeline4_desc: '50k plants in 4 years • carbon-neutral',
    about_vision_title: 'Our Vision',
    about_vision_desc: 'A greener India where every home breathes cleaner air, every balcony grows food, and every child knows how to nurture a plant. We envision 1 million homes with a GreenNest plant by 2030 — without harming the earth.',
    about_vision_b1: 'Cleaner air, healthier lives',
    about_vision_b2: 'Sustainable urban living',
    about_vision_b3: 'Carbon-negative operations by 2028',
    about_mission_title: 'Our Mission',
    about_mission_desc: 'Make plant parenting effortless: organic, affordable, and supported. From pet-safe filters to lifetime WhatsApp help, we remove every barrier between you and your perfect green companion.',
    about_mission_b1: '100% organic, honest pricing',
    about_mission_b2: 'Knowledge for every first-timer',
    about_mission_b3: 'Zero-waste, plastic-free packaging',
    about_values_label: 'Our Values',
    about_value1_title: 'Organic First',
    about_value1_desc: 'No harmful pesticides, natural soil mix, bio-pots.',
    about_value2_title: 'Honesty',
    about_value2_desc: 'Health score for every plant, transparent pricing.',
    about_value3_title: 'Eco Care',
    about_value3_desc: 'Recycled boxes, biodegradable sleeves, carbon-neutral.',
    about_value4_title: 'Support',
    about_value4_desc: 'Lifetime care help — we answer in <2 hrs.',
    // Shop
    shop_title: 'Shop Plants',
    shop_search: 'Search...',
    shop_all_categories: 'All Categories',
    shop_cat_indoor: 'Indoor Plants',
    shop_cat_outdoor: 'Outdoor Plants',
    shop_cat_succulents: 'Succulents',
    shop_cat_flowering: 'Flowering Plants',
    shop_cat_seeds: 'Seeds & Tools',
    shop_newest: 'Newest',
    shop_price_asc: 'Price Low-High',
    shop_price_desc: 'Price High-Low',
    shop_popular_sort: 'Popular',
    shop_sunlight_any: 'Sunlight Any',
    shop_min_price: 'Min ₹',
    shop_max_price: 'Max ₹',
    shop_plants_found: 'plants found',
    shop_prev: 'Prev',
    shop_next: 'Next',
    shop_page: 'Page',
    // PlantDetail
    pd_home: 'Home',
    pd_shop: 'Shop',
    pd_in_stock: 'In Stock',
    pd_out_of_stock: 'Out of Stock',
    pd_stock_badge: 'In Stock',
    pd_reviews_label: 'reviews',
    pd_care: 'care',
    pd_potted_available: '🪴 Potted Available',
    pd_cuttings_available: '✂️ Cuttings Available',
    pd_potted_only: 'Potted only',
    pd_retail: 'Retail',
    pd_wholesale: 'Wholesale',
    pd_single_unit: 'Single unit',
    pd_min_bulk: 'Min bulk qty applies',
    pd_cutting_20: 'CUTTING -20%',
    pd_wholesale_badge: 'WHOLESALE',
    pd_save_vs_potted: 'Save vs potted',
    pd_quantity: 'Quantity',
    pd_total: 'total',
    pd_add_to_cart: 'Add to Cart',
    pd_adding: 'Adding...',
    pd_added: 'Added',
    pd_buy_now: 'Buy Now',
    pd_buying: 'Buying...',
    pd_in_stock_ships: 'In stock • Ships in 24h • Secure: UPI • Card • COD',
    pd_height: 'Height',
    pd_height_val: '25-35 cm',
    pd_pot: 'Pot',
    pd_pot_val: '5 inch',
    pd_pet_safe: 'Pet Safe',
    pd_check_tag: 'Check tag',
    pd_plant_details: 'Plant Details',
    pd_id: 'ID',
    pd_created: 'Created',
    pd_updated: 'Updated',
    pd_short_description: 'Short Description',
    pd_long_description: 'Long Description',
    pd_core_specs: 'Core Specifications — plants',
    pd_care_requirements: 'Care Requirements',
    pd_plant_images: 'Plant Images — plant_images (display_order)',
    pd_shipping_wholesale: 'Shipping & Wholesale',
    pd_sku_label: 'SKU',
    pd_pot_label: 'Pot',
    pd_weight: 'Weight',
    pd_customer_reviews: 'Customer Reviews',
    pd_no_reviews: 'No reviews yet — be the first!',
    pd_write_review: 'Write a review',
    pd_excellent: '★★★★★ Excellent',
    pd_good: '★★★★☆ Good',
    pd_average: '★★★☆☆ Average',
    pd_poor: '★★☆☆☆ Poor',
    pd_bad: '★☆☆☆☆ Bad',
    pd_share_experience: 'Share your experience...',
    pd_submit_review: 'Submit Review',
    pd_login_to_review: 'Please Login to leave a review',
    pd_login: 'Login',
    pd_need_help: 'Need help choosing?',
    pd_need_help_desc: 'Chat with our plant expert on WhatsApp — free lifetime support.',
    pd_chat_whatsapp: 'Chat on WhatsApp',
    pd_delivery_returns: 'Delivery & Returns',
    pd_delivery_2_5: '2-5 day delivery across India',
    pd_secure_payments: 'Secure payments • COD available',
    pd_you_may_also_like: 'You may also like',
    pd_sunlight: 'Sunlight',
    pd_watering: 'Watering Frequency',
    pd_soil: 'Soil Type',
    pd_temp: 'Temperature Range',
    pd_humidity: 'Humidity Preference',
    pd_fertilizer: 'Fertilizer Schedule',
    pd_price_retail: 'Price (Retail)',
    pd_discount_price: 'Discount Price',
    pd_wholesale_price: 'Wholesale Price',
    pd_market_price: 'Market Price',
    pd_stock_qty: 'Stock Qty',
    pd_stock_status: 'Stock Status',
    pd_pet_safe_label: 'Pet Safe',
    pd_growth_rate: 'Growth Rate',
    pd_mature_size: 'Mature Size',
    pd_difficulty: 'Difficulty Level',
    pd_pot_included: 'Pot Included',
    pd_pot_size: 'Pot Size',
    pd_height_shipping: 'Height at Shipping',
    pd_sku_val: 'SKU',
    pd_included: 'Included',
    pd_not_included: 'Not included',
    pd_yes: 'Yes',
    pd_no: 'No',
    pd_table_note: 'Table: plant_images(id, plant_id, image_url, display_order) — sorted by display_order.',
    pd_variant_note: '“With Plastic Pot” and “Cutting” are independent SKUs — no derived math. “Cutting + Plastic Cover” is a separate bundle (₹25–60), not Cutting + cover price.',
    // Cart
    cart_title: 'Your Cart',
    cart_items: 'items',
    cart_item: 'item',
    cart_save_msg: 'You save',
    cart_on_order: 'on this order 🎉',
    cart_free_over: 'Free delivery over ₹999',
    cart_empty_title: 'Your cart is empty',
    cart_empty_desc: 'Looks like you haven\'t added any green friends yet. Explore our bestsellers and bring nature home.',
    cart_go_shopping: 'Go Shopping →',
    cart_back_home: 'Back to Home',
    cart_continue: '← Continue Shopping',
    cart_secure_checkout: '🔒 Secure checkout • UPI • Card • COD',
    cart_add_more_plants: '+ Add more plants',
    cart_order_summary_title: 'Order Summary',
    cart_subtotal_items: 'Subtotal',
    cart_wholesale_saving: '🏢 Wholesale Business Saving',
    cart_note_wholesale: 'Note: Wholesale business amount will be reduced with the quantity.',
    cart_delivery: 'Delivery',
    cart_free: 'FREE',
    cart_savings: 'Savings',
    cart_coupon: 'Coupon code',
    cart_apply: 'Apply',
    cart_total_label: 'Total',
    cart_inclusive: 'Inclusive of taxes',
    cart_proceed: 'Proceed to Checkout →',
    cart_secure_badge: '🔒 100% Secure',
    cart_support_badge: '💬 24/7 Support',
    cart_add_more_free: 'Add ₹',
    cart_more_for_free: 'more for FREE delivery',
    cart_loved: 'Loved by 12k+ plant parents',
    cart_rating: '★ 4.9/5 • Crush-proof packaging',
    cart_you_may_like: 'You may also like',
    cart_complete_corner: 'Complete your green corner',
    cart_total_items_label: 'Total',
    cart_subtotal_label: 'Subtotal',
    cart_save_badge: 'Save',
    cart_wholesale_badge: '🏢 Wholesale',
    cart_business_pricing: 'Business pricing:',
    cart_pcs: 'pcs →',
    cart_each: 'each',
    cart_off: 'off',
    cart_more_qty: 'more qty = lower',
    // Checkout
    checkout_title: 'Checkout',
    checkout_subtitle: 'Add to cart → Fill address → COD only → Owner notified → Thank you',
    checkout_cart_empty_title: 'Cart empty',
    checkout_cart_empty_desc: 'Add plants first',
    checkout_go_shopping: 'Go Shopping',
    checkout_order_placed: 'Order Placed',
    checkout_owner_notified: 'Owner Notified',
    checkout_confirmed: 'Confirmed',
    checkout_order_sent: 'Order Sent! Owner Notified 📲',
    checkout_order_id: 'Order',
    checkout_notification_sent: 'Notification sent to owner\'s mobile +91 98765 43210 via WhatsApp.',
    checkout_what_next: 'What next?',
    checkout_step1: 'Owner reviews stock & delivery area',
    checkout_step2: 'Owner will reply in 30-60 mins (9am-7pm)',
    checkout_step3: 'You\'ll see “Thank you for order and contact soon” here when confirmed',
    checkout_message_owner: 'Message Owner on WhatsApp',
    checkout_simulate: '[Demo] Simulate Owner Reply →',
    checkout_copy_email: 'You\'ll also get copy on',
    checkout_cod_pay: 'COD — pay on delivery',
    checkout_track_dashboard: 'Track in Dashboard →',
    checkout_thank_you: 'Thank you for your order and contact soon! 🎉',
    checkout_owner_replied: 'Owner replied: “Thank you for your order! We will contact you soon to confirm delivery time & address.”',
    checkout_confirmed_title: 'Order Confirmed',
    checkout_call_soon: 'We’ll call you on',
    checkout_within_2h: 'within 2 hours. Keep your phone handy!',
    checkout_cod_badge: 'COD • Pay on delivery',
    checkout_plant_note: 'Plant orders are hand-packed in Pezhummoodu, Thiruvananthapuram, Kerala • GST bill on request',
    checkout_address_title: 'Delivery Address',
    checkout_payment_title: 'Payment Method',
    checkout_payment_desc: 'Online payment removed — pay when you receive the plants. Owner will confirm before dispatch.',
    checkout_cod_desc: 'Pay after delivery — cash / UPI to delivery person. No advance. Owner will call to confirm address & shipping extra (₹39-79 for potted).',
    checkout_no_online: 'No online payment',
    checkout_gst: 'GST bill available',
    checkout_how_it_works_text: 'Place order → Owner gets WhatsApp notification on +91 98765 43210 → Owner replies → You see “Thank you for order and contact soon” → Delivery + COD.',
    checkout_note_cuttings: 'Note: Cuttings ship light & free. Potted extra shipping ₹39-79 (soil weight) added at confirmation. Wholesale bulk extra discount at owner call.',
    checkout_inclusive: 'Inclusive of taxes • Extra potted shipping (₹39-79) confirmed by owner at checkout call.',
    checkout_wholesale_discount: 'Wholesale qty discount applied — more qty = lower unit price.',
    checkout_by_placing: 'By placing, owner gets WhatsApp notification & you get “Thank you and contact soon”',
    checkout_safe: '🔒 COD Safe',
    checkout_replace: '↩️ 14d Replace',
    checkout_owner_call: '💬 Owner Call',
    checkout_owner_mobile_title: 'Owner Mobile: +91 98765 43210',
    checkout_owner_mobile_desc: 'Notification goes instantly on WhatsApp after Place Order',
    checkout_please_login: 'Please Login to save order history. You can still order as guest after login.',
    checkout_login_link: 'Login',
    checkout_edit_below: 'Or edit below manually — changes here don’t overwrite profile unless you save in Dashboard.',
    checkout_potted_shipping: 'Extra potted shipping (₹39-79) confirmed by owner at checkout call.',
    checkout_total: 'Total',
    checkout_shipping_label: 'Shipping',
    checkout_cod_label: 'COD',
    checkout_pay_on_delivery: 'Pay on delivery',
    checkout_placing: 'Placing...',
    // Dashboard
    dash_hello: 'Hello',
    dash_green_family: "Here's what's happening with your green family.",
    dash_download_all: 'Download all care guides',
    dash_total_orders_label: 'Total Orders',
    dash_pending_label: 'Pending',
    dash_awaiting: 'Awaiting confirm',
    dash_delivered_label: 'Delivered',
    dash_completed: 'Completed',
    dash_wishlist_label: 'Wishlist Items',
    dash_saved: 'Saved',
    dash_recent_orders: 'Recent Orders',
    dash_view_all: 'View all →',
    dash_no_orders: 'No orders yet. Your green family awaits!',
    dash_browse_plants: 'Browse plants',
    dash_care_reminders_title: 'Care Reminders',
    dash_no_plants: 'Buy a plant to get personalized care schedule 🌿',
    dash_guide: 'Guide',
    dash_download_care_guides: 'Download care guides (PDF)',
    dash_seasonal: 'Seasonal Reminders 🍂',
    dash_check_drainage: 'Check drainage — monsoon prep',
    dash_mist: 'Mist tropicals 2×/week',
    dash_next: 'Next:',
    dash_fertilize: 'Fertilize on',
    dash_repot: 'Repot in 30 days',
    dash_subscribe: 'Subscribe to alerts',
    dash_my_orders: 'My Orders',
    dash_track_reorder: 'Track, reorder, and download invoices — all in one place',
    dash_all: 'All',
    dash_shipped: 'Shipped',
    dash_cancelled: 'Cancelled',
    dash_view_details: 'View details →',
    dash_hide_details: 'Hide details',
    dash_no_orders_filter: 'No orders in',
    dash_itemized: 'Itemized',
    dash_reorder_btn: 'Reorder • Buy again',
    dash_download_invoice: 'Download invoice',
    dash_cancel_order: 'Cancel order — reason required',
    dash_shipping_address: 'Shipping address',
    dash_tracking: 'Tracking timeline',
    dash_order_placed_timeline: 'Order placed',
    dash_confirmed_timeline: 'Confirmed',
    dash_shipped_timeline: 'Shipped',
    dash_delivered_timeline: 'Delivered',
    dash_cancelled_reason: 'Cancelled — reason',
    dash_my_wishlist: 'My Wishlist',
    dash_saved_wishlist: 'saved',
    dash_browse_plants_wl: 'Browse plants →',
    dash_download_all_guides: 'Download all guides',
    dash_wl_empty_title: 'Your wishlist is empty',
    dash_wl_empty_desc: 'Save your favourites to buy later',
    dash_in_stock: 'In stock',
    dash_out_stock: 'Out of stock',
    dash_move_cart: 'Move to cart',
    dash_remove: 'Remove',
    dash_notify_stock: 'Notify me when back in stock',
    dash_download_care: 'Download care guide PDF',
    dash_saved_addresses: 'Saved Addresses',
    dash_add_new: '+ Add new address',
    dash_home: 'Home',
    dash_work: 'Work',
    dash_other: 'Other',
    dash_use_current: 'Use current location',
    dash_locating: 'Locating...',
    dash_street: 'Street *',
    dash_city_input: 'City *',
    dash_state_input: 'State',
    dash_postal_input: 'Postal Code',
    dash_country_input: 'Country',
    dash_set_default: 'Set as default address',
    dash_pin_preview: 'Pin will appear after you fill city • Map preview',
    dash_save: 'Save address',
    dash_update: 'Update address',
    dash_cancel_btn: 'Cancel',
    dash_no_addresses: 'No addresses saved. Added on checkout — or add one above.',
    dash_default: 'DEFAULT',
    dash_edit: 'Edit',
    dash_delete: 'Delete',
    dash_set_as_default: 'Set as default',
    dash_profile_settings: 'Profile Settings',
    dash_click_avatar: 'Click avatar to change • JPG/PNG max 2MB',
    dash_preview_ready: 'Preview ready — save to apply',
    dash_full_name: 'Full Name',
    dash_phone_number: 'Phone number',
    dash_email: 'Email',
    dash_reverify: '(re-verify if changed)',
    dash_email_changed: '⚠ Email changed — you’ll need to re-verify after saving.',
    dash_notif_prefs: 'Notification preferences',
    dash_order_updates: 'Order updates (SMS/Email)',
    dash_order_updates_desc: 'Shipping, delivery, cancellations',
    dash_promo: 'Promotions & offers',
    dash_promo_desc: 'Seasonal discounts, new arrivals',
    dash_care_emails: 'Care-tip emails',
    dash_care_desc: 'Weekly watering & fertilizing tips',
    dash_save_changes: 'Save changes',
    dash_change_password: 'Change password',
    dash_current_password: 'Current password',
    dash_new_password: 'New password',
    dash_confirm_new: 'Confirm new',
    dash_update_password: 'Update password',
    dash_danger: 'Danger zone — Delete account',
    dash_delete_desc: 'Delete your account and all data. This cannot be undone. Orders will be anonymized.',
    dash_delete_perm: 'Delete account permanently',
    dash_support_history: 'Support ticket history',
    dash_new_query: 'New query — e.g., delivery issue...',
    dash_submit: 'Submit',
    dash_sidebar_profile: 'Profile',
    dash_sidebar_overview: 'Overview',
    dash_sidebar_orders: 'Orders',
    dash_sidebar_wishlist: 'Wishlist',
    dash_sidebar_addresses: 'Addresses',
    dash_sidebar_profile_link: 'Profile',
    dash_continue_shopping: 'Continue Shopping',
    dash_logout: 'Logout',
    dash_need_help_title: 'Need help?',
    dash_need_help_desc: 'Get plant care advice on WhatsApp. Free lifetime support.',
    dash_view_ticket: 'View ticket history',
    dash_profile_complete: 'Profile complete!',
    dash_add_phone: 'add phone number',
    dash_add_address: 'add address',
    // Contact
    contact_badge: 'Get in touch • Reply in 2 hrs',
    contact_hero_title1: "We'd love to",
    contact_hero_title2: 'hear from you',
    contact_hero_desc: 'Questions about a plant, bulk order, or visit our greenhouse? Our growers reply within 2 hours (9am-7pm). Wholesale + retail, single or 250+.',
    contact_phone_display: '📞 +91 98765 43210',
    contact_email_display: '✉ hello@greennest.com',
    contact_whatsapp_display: '💬 WhatsApp us',
    contact_care_expert: 'Meera — Care Expert',
    contact_replies_in: 'Typically replies in 18 mins',
    contact_send_title: 'Send a message',
    contact_send_desc: 'For retail, wholesale (10+ pcs), or greenhouse visit. We reply by email + WhatsApp.',
    contact_sent_success: 'Message sent! Owner notified — you’ll get “Thank you and contact soon” shortly.',
    contact_name_placeholder: 'Priya Sharma',
    contact_email_placeholder: 'you@email.com',
    contact_select_topic: 'Select topic',
    contact_retail: 'Retail Order Help',
    contact_wholesale: 'Wholesale / Bulk (10+ pcs)',
    contact_care_support: 'Plant Care Support',
    contact_greenhouse_visit: 'Greenhouse Visit',
    contact_other: 'Other',
    contact_message_placeholder: 'Hi, I want 25 Aloe Vera potted + 10 cuttings for my nursery near Pezhummoodu, Thiruvananthapuram, Kerala...',
    contact_send_btn: 'Send Message →',
    contact_sending: 'Sending...',
    contact_avg_reply: 'Avg reply 18 mins • Mon-Sat 9am-7pm • Owner mobile gets WhatsApp notification',
    contact_private: '🔒 Private',
    contact_no_spam: '✓ No spam',
    contact_whatsapp_badge: '💬 WhatsApp',
    contact_visit_title: 'Visit our greenhouse',
    contact_greenhouse_name: 'GreenNest Nursery, H34Q+9FP',
    contact_greenhouse_address: 'Poovachal, Kerala 695575 • 2-acre organic farm Open Sat 10am-4pm • Free tour & potting workshop',
    contact_call: '+91 98765 43210',
    contact_call_desc: 'Call / WhatsApp • Mon-Sat 9am-7pm',
    contact_hello_email: 'hello@greennest.com',
    contact_hello_desc: 'Wholesale: bulk@greennest.com • GST invoice',
    contact_whatsapp_us: 'WhatsApp Us →',
    contact_find_map: 'Find us on map',
    contact_poovachal: 'Poovachal • Est 2022',
    contact_open_maps: 'Open in Maps →',
    contact_hours_title: 'Business Hours',
    contact_hours_desc: 'Mon-Sat 9am-7pm • Sun closed • WhatsApp 24h (reply next working hour)',
    contact_select_topic_label: 'Select topic',
    // Footer
    footer_brand_desc: 'Eco-friendly nursery delivering happiness to your doorstep since 2015.',
    footer_quick_links: 'Quick Links',
    footer_shop_link: 'Shop',
    footer_about_link: 'About',
    footer_contact_link: 'Contact',
    footer_contact_title: 'Contact',
    footer_contact_address: '123 Green Lane, Pezhummoodu, TVM, India +91 98765 43210 hello@greennest.com',
    footer_contact_address_line1: '123 Green Lane, Pezhummoodu, TVM, India',
    footer_phone: '+91 98765 43210',
    footer_email: 'hello@greennest.com',
    footer_newsletter: 'Newsletter',
    footer_newsletter_placeholder: 'Your email',
    footer_join: 'Join',
    footer_rights: '© 2026 GreenNest. All rights reserved.',
    footer_subscribed: 'Subscribed — check your email',
    // Auth
    auth_welcome_back: 'Welcome back',
    auth_est: 'Est. 2022 • 12k+ families trust us',
    auth_signin_desc: 'Sign in to track orders, manage addresses and get care support. New here?',
    auth_create_account: 'Create account',
    auth_email_address: 'Email address',
    auth_password: 'Password',
    auth_forgot: 'Forgot?',
    auth_show: 'Show',
    auth_hide: 'Hide',
    auth_keep_signed: 'Keep me signed in',
    auth_sign_in_continue: 'Sign in — Continue →',
    auth_signing_in: 'Signing in...',
    auth_or: 'or',
    auth_continue_google: 'Continue with Google',
    auth_demo: 'Demo:',
    auth_demo_customer: 'Customer → register new • Admin →',
    auth_admin_creds: 'admin@greennest.com / admin123',
    auth_est_badge: 'EST. 2022 • Pezhummoodu, TVM',
    auth_plants_thrive: 'Plants that',
    auth_actually_thrive: 'actually thrive.',
    auth_plants_desc: '4 years, 50k plants, 12k families. Organic since day one, delivered in our crush-proof tubes. Your home deserves better air.',
    auth_quote_name: 'Riya • 2023 customer',
    auth_quote: '“My Aloe still thriving after 2 years!”',
    auth_join_us: 'Join us since',
    auth_join_year: '2022',
    auth_get_off: 'Get 10% off + free care guide. 4 years, 12k families.',
    auth_account: 'Account',
    auth_address: 'Address',
    auth_full_name: 'Full Name',
    auth_phone: 'Phone',
    auth_email: 'Email',
    auth_confirm: 'Confirm',
    auth_strength: 'Strength',
    auth_continue_address: 'Continue to Address →',
    auth_have_account: 'Have account?',
    auth_sign_in: 'Sign in',
    auth_where_deliver: 'Where should we deliver?',
    auth_use_location: 'Use Location',
    auth_street_house: 'Street, House No.',
    auth_city: 'City',
    auth_state: 'State',
    auth_postal: 'Postal Code',
    auth_country: 'Country',
    auth_terms: 'I agree to Terms & Privacy. Est. 2022 GreenNest.',
    auth_back: 'Back',
    auth_create_account_btn: 'Create Account →',
    auth_creating: 'Creating...',
    auth_your_journey: 'Your plant',
    auth_journey_span: 'journey starts here.',
    auth_since_desc: 'Since 2022, we’ve helped 12k families green their homes. Organic, honest, supported for life.',
    auth_perks: 'Perks',
    auth_off_first: '10% off first order',
    auth_track_orders: 'Track orders & saves',
    auth_whatsapp_care: 'WhatsApp care support',
  },
  ml: {
    nav_home: 'ഹോം',
    nav_shop: 'ഷോപ്പ്',
    nav_about: 'ഞങ്ങളെക്കുറിച്ച്',
    nav_contact: 'ബന്ധപ്പെടുക',
    search_placeholder: 'ചെടികൾ തിരയുക...',
    cart: 'കാർട്ട്',
    login: 'ലോഗിൻ',
    signup: 'സൈൻ അപ്പ്',
    logout: 'ലോഗ്ഔട്ട്',
    dashboard: 'ഡാഷ്‌ബോർഡ്',
    continue_shopping: 'ഷോപ്പിംഗ് തുടരുക',
    need_help: 'സഹായം വേണോ?',
    whatsapp_support: 'വാട്ട്‌സാപ്പിൽ പരിചരണ പിന്തുണ — ജീവിതകാലം സൗജന്യം!',
    chat_now: 'ഇപ്പോൾ ചാറ്റ് ചെയ്യുക',
    hello: 'ഹലോ',
    green_family: 'നിങ്ങളുടെ ഹരിത കുടുംബത്തിൽ എന്താണ് സംഭവിക്കുന്നതെന്ന് ഇതാ.',
    total_orders: 'മൊത്തം ഓർഡറുകൾ',
    pending: 'തീർപ്പാക്കാത്തത്',
    delivered: 'വിതരണം ചെയ്തു',
    wishlist: 'വിഷ്‌ലിസ്റ്റ്',
    wallet: 'വാലറ്റ് • ലോയൽറ്റി',
    loved_by_plants: 'ചെടികൾ ഇഷ്ടപ്പെടുന്നു',
    view_rewards: 'റിവാർഡുകൾ കാണുക',
    recent_orders: 'സമീപകാല ഓർഡറുകൾ',
    care_reminders: 'പരിചരണ ഓർമ്മപ്പെടുത്തലുകൾ',
    refer_earn: 'റഫർ ചെയ്ത് നേടുക',
    landscaping_title: 'കേരളത്തിലുടനീളം ഏതുതരം ലാൻഡ്‌സ്‌കേപ്പിംഗ് & ഗാർഡനിംഗ് ചെടികളും',
    landscaping_desc: 'പേഴുംമൂട്, തിരുവനന്തപുരം മുതൽ കാസർഗോഡ് വരെ — ഏതുതരം ലാൻഡ്‌സ്‌കേപ്പിംഗ്, ഗാർഡനിംഗ് ചെടികളും കേരളത്തിലുടനീളം ലഭ്യമാണ്.',
    cancel_reason_required: 'റദ്ദാക്കാനുള്ള കാരണം നിർബന്ധമാണ്',
    cancel_reason_placeholder: 'ഉദാ: തെറ്റായി ഓർഡർ ചെയ്തു, ഡെലിവറി വൈകി...',
    keep_order: 'ഓർഡർ നിലനിർത്തുക',
    confirm_cancel: 'റദ്ദാക്കൽ സ്ഥിരീകരിക്കുക',
    kerala_coverage: 'കേരള വ്യാപക സേവനം • 14 ജില്ലകൾ',
    hero_badge: 'പുതിയ സീസൺ കളക്ഷൻ ലൈവ് — 30% വരെ കിഴിവ്',
    hero_title1: 'ശ്വസിക്കാൻ സഹായിക്കുന്ന',
    hero_title2: 'ചെടികൾ',
    hero_title3: 'നിങ്ങളെ മികച്ചതാക്കുന്നു',
    hero_desc: 'നിങ്ങളുടെ വാതിൽപ്പടിയിൽ എത്തുന്ന ഓർഗാനിക്, നഴ്‌സറി ഫ്രഷ് ചെടികൾ. വെളിച്ചം കുറഞ്ഞ ഇടങ്ങളിൽ വളരുന്നവ മുതൽ വളർത്തുമൃഗങ്ങൾക്ക് സുരക്ഷിതമായ ഇനങ്ങൾ വരെ.',
    shop_collection: 'ഷോപ്പ് കളക്ഷൻ →',
    how_we_grow: 'ഞങ്ങൾ എങ്ങനെ വളർത്തുന്നു',
    best_sellers: 'ഈ ആഴ്ചത്തെ ബെസ്റ്റ് സെല്ലറുകൾ',
    best_sellers_sub: 'സെല്ലറുകൾ',
    filter: 'ഫിൽട്ടർ:',
    popular: 'ജനപ്രിയം',
    new_in: 'പുതിയത്',
    sale: 'വിൽപ്പന',
    view_all_plants: 'എല്ലാ ചെടികളും കാണുക',
    why_love_us: '12k+ പേർ ഞങ്ങളെ സ്നേഹിക്കുന്നത് എന്തുകൊണ്ട്',
    not_just_plant: 'ഒരു ചെടി മാത്രമല്ല.',
    healthy_start: 'ആരോഗ്യകരമായ തുടക്കം.',
    delivery_address: 'ഡെലിവറി വിലാസം',
    fetched_from_profile: 'പ്രൊഫൈലിൽ നിന്ന് എടുത്തത്',
    saved_addresses: 'സേവ് ചെയ്ത വിലാസങ്ങൾ — ടാപ്പ് ചെയ്ത് പൂരിപ്പിക്കുക',
    use_current_location: 'നിലവിലെ ലൊക്കേഷൻ ഉപയോഗിക്കുക',
    street_house: 'തെരുവ്, വീട് നമ്പർ',
    city: 'നഗരം',
    state: 'സംസ്ഥാനം',
    postal_code: 'പിൻ കോഡ്',
    country: 'രാജ്യം',
    phone_owner: 'ഫോൺ (ഉടമയെ ബന്ധപ്പെടാൻ)',
    delivery_note: 'ഡെലിവറി കുറിപ്പ് (ഓപ്ഷണൽ)',
    payment_method: 'പേയ്‌മെന്റ് രീതി',
    online_removed: 'ഓൺലൈൻ പേയ്‌മെന്റ് നീക്കം ചെയ്തു — ചെടികൾ ലഭിക്കുമ്പോൾ പണമടയ്ക്കുക. ഉടമ മുൻകൂട്ടി സ്ഥിരീകരിക്കും.',
    cash_on_delivery: 'ക്യാഷ് ഓൺ ഡെലിവറി (COD)',
    recommended: 'ശുപാർശ ചെയ്തത്',
    pay_after: 'ഡെലിവറിക്ക് ശേഷം പണമടയ്ക്കുക — ക്യാഷ് / UPI. മുൻകൂർ പണമടവ് ഇല്ല. വിലാസവും ഷിപ്പിംഗും (പോട്ടിന് ₹39-79) ഉടമ വിളിച്ച് സ്ഥിരീകരിക്കും.',
    how_it_works: 'എങ്ങനെ പ്രവർത്തിക്കുന്നു:',
    order_summary: 'ഓർഡർ സംഗ്രഹം',
    subtotal: 'സബ്ടോട്ടൽ',
    shipping: 'ഷിപ്പിംഗ്',
    total: 'ആകെ',
    place_order: 'ഓർഡർ നൽകുക — COD →',
    contact_help: 'ഹായ്! നിങ്ങളുടെ കിടപ്പുമുറിക്ക് കുറഞ്ഞ വെളിച്ചത്തിൽ വളരുന്ന ചെടി തിരഞ്ഞെടുക്കാൻ സഹായം വേണോ? 3 വളർത്തുമൃഗ സുരക്ഷിത ഓപ്ഷനുകൾ നിർദ്ദേശിക്കാം 🌿',
    send_message: 'സന്ദേശം അയയ്ക്കുക',
    your_name: 'നിങ്ങളുടെ പേര്',
    email: 'ഇമെയിൽ',
    subject: 'വിഷയം',
    message: 'സന്ദേശം',
    send: 'അയയ്ക്കുക →',
    visit_greenhouse: 'ഞങ്ങളുടെ നഴ്‌സറി സന്ദർശിക്കുക',
    find_us_map: 'മാപ്പിൽ ഞങ്ങളെ കണ്ടെത്തുക',
    landing_best_title: 'ഈ ആഴ്ചത്തെ ബെസ്റ്റ് സെല്ലറുകൾ',
    landing_sale_badge: 'വിൽപ്പന',
    landing_variants_fixed: 'വകഭേദങ്ങൾ • നിശ്ചിതം',
    landing_stock_left: 'ബാക്കി',
    landing_stock_label: 'സ്റ്റോക്ക്:',
    landing_options: 'ഓപ്ഷനുകൾ',
    landing_fixed: 'നിശ്ചിതം',
    landing_with_pot: 'പ്ലാസ്റ്റിക് പോട്ടിനൊപ്പം • നിശ്ചിതം',
    landing_add_to_cart: 'കാർട്ടിൽ ചേർക്കുക',
    landing_loading: 'ബെസ്റ്റ് സെല്ലറുകൾ ലോഡ് ചെയ്യുന്നു...',
    landing_landscaping_desc2: 'പേഴുംമൂട്, തിരുവനന്തപുരം മുതൽ കാസർഗോഡ് വരെ — ഏത് ലാൻഡ്‌സ്‌കേപ്പിംഗ്, റൂഫ്‌ടോപ്പ്, ബാൽക്കണി, ഇൻഡോർ ചെടികളും. ഞങ്ങളുടെ 2 ഏക്കർ നഴ്‌സറിയിൽ നിന്ന് നേരിട്ട്, 3-5 ദിവസ ഡെലിവറി, GST ബില്ലും പരിചരണ പിന്തുണയും.',
    landing_residential: '✓ റസിഡൻഷ്യൽ വില്ലകൾ',
    landing_offices: '✓ ഓഫീസുകളും ഹോട്ടലുകളും',
    landing_schools: '✓ സ്കൂളുകളും റിസോർട്ടുകളും',
    landing_nurseries: '✓ നഴ്‌സറികളും പ്രോജക്റ്റുകളും',
    landing_districts1: 'ടിവിഎം • കൊല്ലം • പത്തനംതിട്ട • ആലപ്പുഴ',
    landing_districts2: 'കോട്ടയം • ഇടുക്കി • എറണാകുളം • തൃശൂർ',
    landing_districts3: 'പാലക്കാട് • മലപ്പുറം • കോഴിക്കോട് • വയനാട് • കണ്ണൂർ • കാസർഗോഡ്',
    landing_get_quote: 'ലാൻഡ്‌സ്‌കേപ്പിംഗ് ക്വോട്ട് നേടുക →',
    landing_browse_plants: 'ചെടികൾ ബ്രൗസ് ചെയ്യുക',
    landing_base_location: 'ബേസ്: H34Q+9FP, പേഴുംമൂട്, തിരുവനന്തപുരം, കേരളം 695575 • പാൻ-കേരള ഡെലിവറി • ഇൻസ്റ്റാളേഷൻ ടീം ലഭ്യം',
    landing_garden_title: 'ഗാർഡൻ ലാൻഡ്‌സ്‌കേപ്പിംഗ്',
    landing_garden_desc: 'ലോൺ, ഹെഡ്ജുകൾ, പനകൾ, പൂക്കൾ',
    landing_balcony_title: 'ബാൽക്കണി & ടെറസ്',
    landing_balcony_desc: 'വായു ശുദ്ധീകരിക്കുന്ന ഇൻഡോർ',
    landing_office_title: 'ഓഫീസ് / റിസോർട്ട്',
    landing_office_desc: 'അരെക്ക, ലക്കി ബാംബൂ, കലാത്തിയ',
    landing_all_kerala: 'എല്ലാ കേരളവും',
    landing_all_kerala_desc: 'ഏത് ചെടിയും, ഏത് അളവും — വിതരണവും ഇൻസ്റ്റാളേഷനും. 14 ജില്ലകൾ, 3-5 ദിവസം.',
    landing_pezhummoodu: 'പേഴുംമൂട് → എല്ലായിടത്തും',
    landing_nursery_fresh_title: '48 മണിക്കൂറിൽ നഴ്‌സറി-ഫ്രഷ്',
    landing_nursery_fresh_desc: 'പേഴുംമൂട്, തിരുവനന്തപുരം, കേരള ഹരിതഗൃഹത്തിൽ നിന്ന് ഇടനിലക്കാരില്ലാതെ തിരഞ്ഞെടുത്ത് പാക്ക് ചെയ്ത് അയച്ചു.',
    landing_organic_title: 'ഓർഗാനിക് & സുരക്ഷിതം',
    landing_organic_desc: 'ഹാനികരമായ കീടനാശിനികളില്ല. വളർത്തുമൃഗ & കുട്ടി സൗഹൃദം.',
    landing_expert_title: 'വിദഗ്ധ പരിചരണ പിന്തുണ',
    landing_expert_desc: 'ജീവിതകാലം സൗജന്യ വാട്ട്‌സാപ്പ് സഹായം.',
    landing_safe_title: 'സുരക്ഷിത എത്തിച്ചേരൽ ഗ്യാരണ്ടി',
    landing_safe_desc: 'ക്രഷ്-പ്രൂഫ്, ശ്വസിക്കാവുന്ന പാക്കേജിംഗ്. കേടായാൽ മാറ്റം.',
    landing_eco_title: 'ഇക്കോ പാക്കേജിംഗ്',
    landing_eco_desc: 'പ്ലാസ്റ്റിക് രഹിത, ബയോഡീഗ്രേഡബിൾ പോട്ടുകളും റീസൈക്കിൾ ബോക്സുകളും.',
    landing_our_story: 'ഞങ്ങളുടെ കഥ',
    landing_reviews_rating: '★ 4.9/5 3,421 അവലോകനങ്ങളിൽ നിന്ന്',
    landing_direct_badge: 'ഞങ്ങളുടെ ഹരിതഗൃഹത്തിൽ നിന്ന് നേരിട്ട്',
    landing_grown_title1: 'കരുതലോടെ വളർത്തിയത്.',
    landing_grown_title2: 'സ്നേഹത്തോടെ വിതരണം.',
    landing_grown_desc: 'ഇടനിലക്കാരില്ല. പേഴുംമൂട്, തിരുവനന്തപുരത്തെ 2 ഏക്കർ ഓർഗാനിക് നഴ്‌സറിയിൽ നിന്ന് 3 ദിവസത്തിനുള്ളിൽ നിങ്ങളുടെ വീട്ടിൽ. ഓരോ ചെടിയും കൈകൊണ്ട് തിരഞ്ഞെടുത്ത്, ആരോഗ്യം പരിശോധിച്ച് ജീവനോടെ പാക്ക് ചെയ്യുന്നു.',
    curated_badge: 'ഞങ്ങളുടെ 2 ഏക്കർ നഴ്‌സറിയിൽ നിന്ന് ഫ്രഷ്',
    curated_title1: 'കരുതലോടെ വളർത്തിയത്.',
    curated_title2: 'നിങ്ങളുടെ ഇടത്തിന് ചേർന്നത്.',
    curated_desc: 'പേഴുംമൂടത്ത് കൈകൊണ്ട് തിരഞ്ഞെടുത്ത്, ആരോഗ്യം പരിശോധിച്ച് ലൈവ് പാക്ക് ചെയ്യുന്നു. ടെറസ്സ് മുതൽ സ്വീകരണമുറി വരെ — വെളിച്ചത്തിനും സ്ഥലത്തിനും ജീവിതശൈലിക്കും ചേരുന്ന പച്ചപ്പ് ഞങ്ങൾ ഒരുക്കും.',
    curated_feature_badge: 'ലിവിങ് ഇൻസ്റ്റലേഷൻസ്',
    curated_feature_title: 'ഗാർഡൻ & ലാൻഡ്‌സ്‌കേപ്പ് ഡിസൈൻ ചെയ്തുനൽകുന്നു',
    curated_feature_desc: 'ലോൺ, ഹെഡ്ജ്, പനകൾ, പൂച്ചെടികൾ — ഞങ്ങളുടെ ടീം സ്ഥലത്തെത്തി ഡിസൈൻ ചെയ്ത് നട്ട് റെഡി ഗാർഡൻ കൈമാറും, 2–3 സന്ദർശനത്തിൽ.',
    curated_feature_cta1: 'സൗജന്യ സന്ദർശനം നേടുക →',
    curated_feature_cta2: 'ചെടികൾ കാണുക',
    curated_balcony_label: 'ബാൽക്കണി & ടെറസ്',
    curated_balcony_title: 'ചെറിയ ഇടം, വലിയ പച്ചപ്പ്',
    curated_balcony_desc: 'കുറഞ്ഞ വെളിച്ചം, കാറ്റ്, വെയിൽ എന്നിവയ്ക്ക് വായു ശുദ്ധീകരിക്കുന്ന തിരഞ്ഞെടുപ്പുകൾ.',
    curated_office_label: 'ഓഫീസുകളും ഹോട്ടലുകളും',
    curated_office_title: 'ശാന്തം, പ്രീമിയം, പരിപാലനം കുറവ്',
    curated_office_desc: 'അരേക്ക, കലാത്തിയ, ലക്കി ബാംബൂ — സ്റ്റേറ്റ്മെന്റ് ചെടികൾ.',
    curated_stat_homes: 'വീടുകൾ പച്ചപ്പാക്കി',
    curated_stat_rating: 'അവലോകനങ്ങൾ',
    curated_stat_eta: 'നഴ്‌സറി → വീട്',
    curated_stat_nursery: 'ഓർഗാനിക് നഴ്‌സറി',
    curated_footer_note: 'GST ബിൽ • 3–5 ദിവസ ഡെലിവറി • ഇൻസ്റ്റലേഷൻ ടീം ലഭ്യം',
    landing_stat_48h: '48മ',
    landing_stat_48h_label: 'നഴ്‌സറി മുതൽ വീട്ടിൽ',
    landing_stat_damage: '0.8%',
    landing_stat_damage_label: 'കേടുപാട് നിരക്ക്',
    landing_stat_replace: '14ദി',
    landing_stat_replace_label: 'മാറ്റ ഗ്യാരണ്ടി',
    landing_meet_growers: 'കർഷകരെ കാണുക →',
    landing_shop_live: 'ജീവനുള്ള ചെടികൾ വാങ്ങുക',
    landing_handpicked_title: 'കൈകൊണ്ട് തിരഞ്ഞെടുത്തത്',
    landing_handpicked_desc: 'ആരോഗ്യ സ്കോർ 9/10. മികച്ച ഇലകൾ മാത്രം.',
    landing_livepacked_title: 'ജീവനോടെ പാക്ക് ചെയ്തത്',
    landing_livepacked_desc: 'ശ്വസിക്കാവുന്ന ട്യൂബ്, കോക്കോ-പീറ്റ്.',
    landing_qr_title: 'QR പരിചരണം',
    landing_qr_desc: 'നന, വെളിച്ചം, വളർത്തുമൃഗ ഗൈഡിനായി സ്കാൻ ചെയ്യുക.',
    landing_lifetime_title: 'ജീവിതകാല സഹായം',
    landing_lifetime_desc: 'വാട്ട്‌സാപ്പിൽ കർഷകരെ ബന്ധപ്പെടുക — സൗജന്യം.',
    landing_quote: '“ചെടികൾ നഴ്‌സറിയിൽ നിന്ന് നേരിട്ട് വന്നതുപോലെ”',
    landing_quote_author: '— പ്രിയ എസ്., മുംബൈ • 12 ഓർഡറുകൾ',
    landing_newsletter_badge: 'ക്ലബ്ബിൽ ചേരുക',
    landing_newsletter_title1: '10% കിഴിവ് + സൗജന്യ',
    landing_newsletter_title2: 'പരിചരണ ഗൈഡ് PDF',
    landing_newsletter_desc: 'സ്പാം ഇല്ല. എപ്പോൾ വേണമെങ്കിലും അൺസബ്‌സ്‌ക്രൈബ് ചെയ്യാം. 12,000+ പേരുണ്ട്.',
    landing_your_email: 'നിങ്ങളുടെ ഇമെയിൽ',
    landing_join: 'ചേരുക →',
    about_badge: 'ഗ്രീൻനെസ്റ്റിനെക്കുറിച്ച് • 2022 പേഴുംമൂട്, ടിവിഎം',
    about_hero_title1: 'ഞങ്ങൾ സന്തോഷം വളർത്തുന്നു,',
    about_hero_title2: 'ഒരു സമയം ഒരു ചെടി.',
    about_hero_desc: '2022 മുതൽ, കോത്രുഡിലെ 200 ചതുരശ്ര അടി നഴ്‌സറിയിൽ നിന്ന് ഇന്ത്യയിലുടനീളം 12,000+ വീടുകളിലേക്ക് — ഓർഗാനിക് പരിചരണം, സത്യസന്ധമായ വില, ജീവിതകാല പിന്തുണ.',
    about_shop_plants: 'ചെടികൾ വാങ്ങുക →',
    about_our_story: 'ഞങ്ങളുടെ കഥ',
    about_stats_plants: 'വിതരണം ചെയ്ത ചെടികൾ',
    about_stats_reviews: '3,421 അവലോകനങ്ങൾ',
    about_stats_families: 'സന്തുഷ്ട കുടുംബങ്ങൾ',
    about_organic_title: 'ആദ്യം മുതൽ ഓർഗാനിക്',
    about_organic_desc: 'കീടനാശിനികളില്ല • ഇക്കോ പോട്ടുകൾ • കാർബൺ-ന്യൂട്രൽ',
    about_story_label: 'ഞങ്ങളുടെ കഥ',
    about_story_title1: 'ഒരു ആശയത്തിന്റെ വിത്തിൽ നിന്ന്',
    about_story_title2: 'വീടുകളുടെ വനത്തിലേക്ക്.',
    about_story_p1: '2022 — ചെറിയ തുടക്കം. സ്ഥാപക ആശ പട്ടേൽ, ബോട്ടണി ബിരുദധാരി, ബാൽക്കണിയിൽ 80 മാതൃ ചെടികളുമായി തുടങ്ങി, പേഴുംമൂട്, ടിവിഎം കർഷക മാർക്കറ്റുകളിൽ വിൽപന.',
    about_story_p2: '2023 — ഹരിതഗൃഹം. മുൾഷിയിൽ 2 ഏക്കർ ഓർഗാനിക് ഹരിതഗൃഹം, രാസവസ്തുക്കളില്ലാത്ത മണ്ണ്, മഴവെള്ള സംഭരണം, 5 വനിതാ കർഷകർ. ക്രഷ്-പ്രൂഫ് ട്യൂബുകൾ — കേടുപാട് 12% ൽ നിന്ന് 0.8% ആയി.',
    about_story_p3: '2024 — ഡിജിറ്റൽ വളർച്ച. പരിചരണ വീഡിയോകൾ, വാട്ട്‌സാപ്പ് പിന്തുണ, QR കെയർ കാർഡുകളുമായി GreenNest.in ലോഞ്ച്.',
    about_story_p4: 'ഇന്ന് — 2026. 50k+ ചെടികൾ, 12k+ കുടുംബങ്ങൾ, 4.9★ റേറ്റിംഗ് 4 വർഷത്തിനുള്ളിൽ. ഇപ്പോഴും കുടുംബം നടത്തുന്നു, ഓർഗാനിക്.',
    about_year_2022: '80 ചെടികൾ, 1 ബാൽക്കണി',
    about_year_2026: '2 ഏക്കർ, 50k+ ചെടികൾ • 4 വർഷം',
    about_promise: 'ഞങ്ങളുടെ വാഗ്ദാനം: ആരോഗ്യമുള്ള, ഓർഗാനിക് ചെടികൾ + ജീവിതകാല പിന്തുണ.',
    about_timeline1_title: 'ആശയം വിതച്ചു',
    about_timeline1_desc: 'ബാൽക്കണി നഴ്‌സറി, മാർക്കറ്റ് അരങ്ങേറ്റം',
    about_timeline2_title: 'ഹരിതഗൃഹം',
    about_timeline2_desc: 'മുൾഷി ഓർഗാനിക് ഫാം, ട്യൂബ് പാക്കേജിംഗ്',
    about_timeline3_title: 'ഓൺലൈൻ സ്റ്റോർ',
    about_timeline3_desc: 'പാൻ-ഇന്ത്യ ഡെലിവറി, QR ഗൈഡുകൾ',
    about_timeline4_title: '12k കുടുംബങ്ങൾ',
    about_timeline4_desc: '4 വർഷത്തിൽ 50k ചെടികൾ • കാർബൺ-ന്യൂട്രൽ',
    about_vision_title: 'ഞങ്ങളുടെ ദർശനം',
    about_vision_desc: 'ഓരോ വീടും ശുദ്ധവായു ശ്വസിക്കുന്ന, ഓരോ ബാൽക്കണിയും ഭക്ഷണം വളർത്തുന്ന, ഓരോ കുട്ടിയും ചെടി പരിപാലിക്കാൻ അറിയുന്ന ഹരിത ഇന്ത്യ.',
    about_vision_b1: 'ശുദ്ധവായു, ആരോഗ്യകരമായ ജീവിതം',
    about_vision_b2: 'സുസ്ഥിര നഗര ജീവിതം',
    about_vision_b3: '2028 ആകുമ്പോൾ കാർബൺ-നെഗറ്റീവ്',
    about_mission_title: 'ഞങ്ങളുടെ ദൗത്യം',
    about_mission_desc: 'ചെടി പരിപാലനം എളുപ്പമാക്കുക: ഓർഗാനിക്, താങ്ങാവുന്ന, പിന്തുണയുള്ളത്. വളർത്തുമൃഗ സുരക്ഷ മുതൽ ജീവിതകാല വാട്ട്‌സാപ്പ് സഹായം വരെ.',
    about_mission_b1: '100% ഓർഗാനിക്, സത്യസന്ധമായ വില',
    about_mission_b2: 'ആദ്യമായി വളർത്തുന്നവർക്കുള്ള അറിവ്',
    about_mission_b3: 'സീറോ-വേസ്റ്റ്, പ്ലാസ്റ്റിക് രഹിത പാക്കേജിംഗ്',
    about_values_label: 'ഞങ്ങളുടെ മൂല്യങ്ങൾ',
    about_value1_title: 'ഓർഗാനിക് ആദ്യം',
    about_value1_desc: 'ഹാനികരമായ കീടനാശിനികളില്ല, സ്വാഭാവിക മണ്ണ്.',
    about_value2_title: 'സത്യസന്ധത',
    about_value2_desc: 'ഓരോ ചെടിക്കും ആരോഗ്യ സ്കോർ, സുതാര്യമായ വില.',
    about_value3_title: 'ഇക്കോ കെയർ',
    about_value3_desc: 'റീസൈക്കിൾ ബോക്സുകൾ, ബയോഡീഗ്രേഡബിൾ.',
    about_value4_title: 'പിന്തുണ',
    about_value4_desc: 'ജീവിതകാല സഹായം — 2 മണിക്കൂറിനുള്ളിൽ മറുപടി.',
    shop_title: 'ചെടികൾ വാങ്ങുക',
    shop_search: 'തിരയുക...',
    shop_all_categories: 'എല്ലാ വിഭാഗങ്ങളും',
    shop_cat_indoor: 'ഇൻഡോർ ചെടികൾ',
    shop_cat_outdoor: 'ഔട്ട്ഡോർ ചെടികൾ',
    shop_cat_succulents: 'സക്യുലന്റ്സ്',
    shop_cat_flowering: 'പൂക്കുന്ന ചെടികൾ',
    shop_cat_seeds: 'വിത്തുകളും ഉപകരണങ്ങളും',
    shop_newest: 'പുതിയത്',
    shop_price_asc: 'വില കുറഞ്ഞത്-കൂടിയത്',
    shop_price_desc: 'വില കൂടിയത്-കുറഞ്ഞത്',
    shop_popular_sort: 'ജനപ്രിയം',
    shop_sunlight_any: 'വെളിച്ചം ഏതും',
    shop_min_price: 'കുറഞ്ഞ ₹',
    shop_max_price: 'കൂടിയ ₹',
    shop_plants_found: 'ചെടികൾ കണ്ടെത്തി',
    shop_prev: 'മുമ്പ്',
    shop_next: 'അടുത്തത്',
    shop_page: 'പേജ്',
    pd_home: 'ഹോം',
    pd_shop: 'ഷോപ്പ്',
    pd_in_stock: 'സ്റ്റോക്കിൽ ഉണ്ട്',
    pd_out_of_stock: 'സ്റ്റോക്കില്ല',
    pd_stock_badge: 'സ്റ്റോക്കിൽ',
    pd_reviews_label: 'അവലോകനങ്ങൾ',
    pd_care: 'പരിചരണം',
    pd_potted_available: '🪴 പോട്ടിൽ ലഭ്യം',
    pd_cuttings_available: '✂️ കട്ടിംഗ്സ് ലഭ്യം',
    pd_potted_only: 'പോട്ടിൽ മാത്രം',
    pd_retail: 'റീട്ടെയിൽ',
    pd_wholesale: 'ഹോൾസെയിൽ',
    pd_single_unit: 'ഒറ്റ യൂണിറ്റ്',
    pd_min_bulk: 'ബൾക്ക് അളവ് ബാധകം',
    pd_cutting_20: 'കട്ടിംഗ് -20%',
    pd_wholesale_badge: 'ഹോൾസെയിൽ',
    pd_save_vs_potted: 'പോട്ടിനേക്കാൾ ലാഭം',
    pd_quantity: 'അളവ്',
    pd_total: 'ആകെ',
    pd_add_to_cart: 'കാർട്ടിൽ ചേർക്കുക',
    pd_adding: 'ചേർക്കുന്നു...',
    pd_added: 'ചേർത്തു',
    pd_buy_now: 'ഇപ്പോൾ വാങ്ങുക',
    pd_buying: 'വാങ്ങുന്നു...',
    pd_in_stock_ships: 'സ്റ്റോക്കിൽ • 24 മണിക്കൂറിൽ ഷിപ്പ് • സുരക്ഷിതം: UPI • കാർഡ് • COD',
    pd_height: 'ഉയരം',
    pd_height_val: '25-35 സെ.മീ',
    pd_pot: 'പോട്ട്',
    pd_pot_val: '5 ഇഞ്ച്',
    pd_pet_safe: 'വളർത്തുമൃഗ സുരക്ഷ',
    pd_check_tag: 'ടാഗ് പരിശോധിക്കുക',
    pd_plant_details: 'ചെടിയുടെ വിശദാംശങ്ങൾ',
    pd_id: 'ഐഡി',
    pd_created: 'സൃഷ്ടിച്ചത്',
    pd_updated: 'അപ്ഡേറ്റ് ചെയ്തത്',
    pd_short_description: 'ചെറു വിവരണം',
    pd_long_description: 'വിശദ വിവരണം',
    pd_core_specs: 'കോർ സ്പെസിഫിക്കേഷനുകൾ',
    pd_care_requirements: 'പരിചരണ ആവശ്യങ്ങൾ',
    pd_plant_images: 'ചെടി ചിത്രങ്ങൾ',
    pd_shipping_wholesale: 'ഷിപ്പിംഗ് & ഹോൾസെയിൽ',
    pd_sku_label: 'SKU',
    pd_pot_label: 'പോട്ട്',
    pd_weight: 'ഭാരം',
    pd_customer_reviews: 'ഉപഭോക്തൃ അവലോകനങ്ങൾ',
    pd_no_reviews: 'അവലോകനങ്ങളില്ല — ആദ്യത്തെയാകൂ!',
    pd_write_review: 'അവലോകനം എഴുതുക',
    pd_excellent: '★★★★★ മികച്ചത്',
    pd_good: '★★★★☆ നല്ലത്',
    pd_average: '★★★☆☆ ശരാശരി',
    pd_poor: '★★☆☆☆ മോശം',
    pd_bad: '★☆☆☆☆ വളരെ മോശം',
    pd_share_experience: 'നിങ്ങളുടെ അനുഭവം പങ്കിടുക...',
    pd_submit_review: 'അവലോകനം സമർപ്പിക്കുക',
    pd_login_to_review: 'അവലോകനം ഇടാൻ ലോഗിൻ ചെയ്യുക',
    pd_login: 'ലോഗിൻ',
    pd_need_help: 'തിരഞ്ഞെടുക്കാൻ സഹായം വേണോ?',
    pd_need_help_desc: 'വാട്ട്‌സാപ്പിൽ ഞങ്ങളുടെ വിദഗ്ധരുമായി ചാറ്റ് ചെയ്യുക — സൗജന്യം.',
    pd_chat_whatsapp: 'വാട്ട്‌സാപ്പിൽ ചാറ്റ് ചെയ്യുക',
    pd_delivery_returns: 'ഡെലിവറി & റിട്ടേൺ',
    pd_delivery_2_5: 'ഇന്ത്യയിലുടനീളം 2-5 ദിവസ ഡെലിവറി',
    pd_secure_payments: 'സുരക്ഷിത പേയ്‌മെന്റുകൾ • COD ലഭ്യം',
    pd_you_may_also_like: 'നിങ്ങൾക്ക് ഇഷ്ടപ്പെട്ടേക്കാം',
    pd_sunlight: 'സൂര്യപ്രകാശം',
    pd_watering: 'നനവ് ആവൃത്തി',
    pd_soil: 'മണ്ണിന്റെ തരം',
    pd_temp: 'താപനില പരിധി',
    pd_humidity: 'ഈർപ്പം',
    pd_fertilizer: 'വള ഷെഡ്യൂൾ',
    pd_price_retail: 'വില (റീട്ടെയിൽ)',
    pd_discount_price: 'കിഴിവ് വില',
    pd_wholesale_price: 'ഹോൾസെയിൽ വില',
    pd_market_price: 'മാർക്കറ്റ് വില',
    pd_stock_qty: 'സ്റ്റോക്ക് അളവ്',
    pd_stock_status: 'സ്റ്റോക്ക് സ്ഥിതി',
    pd_pet_safe_label: 'വളർത്തുമൃഗ സുരക്ഷ',
    pd_growth_rate: 'വളർച്ചാ നിരക്ക്',
    pd_mature_size: 'പക്വ വലുപ്പം',
    pd_difficulty: 'ബുദ്ധിമുട്ട്',
    pd_pot_included: 'പോട്ട് ഉൾപ്പെടെ',
    pd_pot_size: 'പോട്ട് വലുപ്പം',
    pd_height_shipping: 'ഷിപ്പിംഗ് ഉയരം',
    pd_sku_val: 'SKU',
    pd_included: 'ഉൾപ്പെടെ',
    pd_not_included: 'ഉൾപ്പെടുന്നില്ല',
    pd_yes: 'അതെ',
    pd_no: 'അല്ല',
    pd_table_note: 'പട്ടിക: plant_images(id, plant_id, image_url, display_order)',
    pd_variant_note: '“പ്ലാസ്റ്റിക് പോട്ടിനൊപ്പം” “കട്ടിംഗ്” എന്നിവ സ്വതന്ത്ര SKU-കളാണ്.',
    cart_title: 'നിങ്ങളുടെ കാർട്ട്',
    cart_items: 'ഇനങ്ങൾ',
    cart_item: 'ഇനം',
    cart_save_msg: 'നിങ്ങൾ ലാഭിക്കുന്നു',
    cart_on_order: 'ഈ ഓർഡറിൽ 🎉',
    cart_free_over: '₹999 ന് മുകളിൽ സൗജന്യ ഡെലിവറി',
    cart_empty_title: 'നിങ്ങളുടെ കാർട്ട് ശൂന്യമാണ്',
    cart_empty_desc: 'നിങ്ങൾ ഒരു ചെടിയും ചേർത്തിട്ടില്ല. ബെസ്റ്റ് സെല്ലറുകൾ കാണുക.',
    cart_go_shopping: 'ഷോപ്പിംഗിന് പോകുക →',
    cart_back_home: 'ഹോമിലേക്ക് മടങ്ങുക',
    cart_continue: '← ഷോപ്പിംഗ് തുടരുക',
    cart_secure_checkout: '🔒 സുരക്ഷിത ചെക്ക്ഔട്ട് • UPI • കാർഡ് • COD',
    cart_add_more_plants: '+ കൂടുതൽ ചെടികൾ ചേർക്കുക',
    cart_order_summary_title: 'ഓർഡർ സംഗ്രഹം',
    cart_subtotal_items: 'സബ്ടോട്ടൽ',
    cart_wholesale_saving: '🏢 ഹോൾസെയിൽ ലാഭം',
    cart_note_wholesale: 'കുറിപ്പ്: ഹോൾസെയിൽ തുക അളവിനനുസരിച്ച് കുറയും.',
    cart_delivery: 'ഡെലിവറി',
    cart_free: 'സൗജന്യം',
    cart_savings: 'ലാഭം',
    cart_coupon: 'കൂപ്പൺ കോഡ്',
    cart_apply: 'പ്രയോഗിക്കുക',
    cart_total_label: 'ആകെ',
    cart_inclusive: 'നികുതികൾ ഉൾപ്പെടെ',
    cart_proceed: 'ചെക്ക്ഔട്ടിലേക്ക് പോകുക →',
    cart_secure_badge: '🔒 100% സുരക്ഷിതം',
    cart_support_badge: '💬 24/7 പിന്തുണ',
    cart_add_more_free: '₹',
    cart_more_for_free: 'കൂടി ചേർത്താൽ സൗജന്യ ഡെലിവറി',
    cart_loved: '12k+ പേർ ഇഷ്ടപ്പെടുന്നു',
    cart_rating: '★ 4.9/5 • ക്രഷ്-പ്രൂഫ് പാക്കേജിംഗ്',
    cart_you_may_like: 'നിങ്ങൾക്ക് ഇഷ്ടപ്പെട്ടേക്കാം',
    cart_complete_corner: 'നിങ്ങളുടെ പച്ച മൂല പൂർത്തിയാക്കുക',
    cart_total_items_label: 'ആകെ',
    cart_subtotal_label: 'സബ്ടോട്ടൽ',
    cart_save_badge: 'ലാഭം',
    cart_wholesale_badge: '🏢 ഹോൾസെയിൽ',
    cart_business_pricing: 'ബിസിനസ് വില:',
    cart_pcs: 'എണ്ണം →',
    cart_each: 'ഓരോന്നിനും',
    cart_off: 'കിഴിവ്',
    cart_more_qty: 'കൂടുതൽ അളവ് = കുറഞ്ഞ വില',
    checkout_title: 'ചെക്ക്ഔട്ട്',
    checkout_subtitle: 'കാർട്ടിൽ ചേർക്കുക → വിലാസം പൂരിപ്പിക്കുക → COD → ഉടമ അറിയിക്കും → നന്ദി',
    checkout_cart_empty_title: 'കാർട്ട് ശൂന്യം',
    checkout_cart_empty_desc: 'ആദ്യം ചെടികൾ ചേർക്കുക',
    checkout_go_shopping: 'ഷോപ്പിംഗിന് പോകുക',
    checkout_order_placed: 'ഓർഡർ നൽകി',
    checkout_owner_notified: 'ഉടമയെ അറിയിച്ചു',
    checkout_confirmed: 'സ്ഥിരീകരിച്ചു',
    checkout_order_sent: 'ഓർഡർ അയച്ചു! ഉടമയെ അറിയിച്ചു 📲',
    checkout_order_id: 'ഓർഡർ',
    checkout_notification_sent: 'ഉടമയുടെ മൊബൈലിലേക്ക് വാട്ട്‌സാപ്പ് വഴി അറിയിപ്പ് അയച്ചു +91 98765 43210.',
    checkout_what_next: 'അടുത്തതെന്ത്?',
    checkout_step1: 'ഉടമ സ്റ്റോക്കും ഡെലിവറി ഏരിയയും പരിശോധിക്കുന്നു',
    checkout_step2: 'ഉടമ 30-60 മിനിറ്റിനുള്ളിൽ മറുപടി നൽകും (9am-7pm)',
    checkout_step3: 'സ്ഥിരീകരിക്കുമ്പോൾ “ഓർഡറിന് നന്ദി, ഉടൻ ബന്ധപ്പെടാം” ഇവിടെ കാണാം',
    checkout_message_owner: 'വാട്ട്‌സാപ്പിൽ ഉടമയെ ബന്ധപ്പെടുക',
    checkout_simulate: '[ഡെമോ] ഉടമയുടെ മറുപടി അനുകരിക്കുക →',
    checkout_copy_email: 'നിങ്ങൾക്ക് പകർപ്പ് ലഭിക്കും',
    checkout_cod_pay: 'COD — ഡെലിവറിയിൽ പണമടയ്ക്കുക',
    checkout_track_dashboard: 'ഡാഷ്‌ബോർഡിൽ ട്രാക്ക് ചെയ്യുക →',
    checkout_thank_you: 'നിങ്ങളുടെ ഓർഡറിന് നന്ദി, ഉടൻ ബന്ധപ്പെടാം! 🎉',
    checkout_owner_replied: 'ഉടമ മറുപടി നൽകി: “നിങ്ങളുടെ ഓർഡറിന് നന്ദി! ഡെലിവറി സമയവും വിലാസവും സ്ഥിരീകരിക്കാൻ ഉടൻ ബന്ധപ്പെടാം.”',
    checkout_confirmed_title: 'ഓർഡർ സ്ഥിരീകരിച്ചു',
    checkout_call_soon: 'ഞങ്ങൾ നിങ്ങളെ വിളിക്കും',
    checkout_within_2h: '2 മണിക്കൂറിനുള്ളിൽ. ഫോൺ കൈയിലിരിക്കട്ടെ!',
    checkout_cod_badge: 'COD • ഡെലിവറിയിൽ പണമടയ്ക്കുക',
    checkout_plant_note: 'ചെടി ഓർഡറുകൾ പേഴുംമൂട്, തിരുവനന്തപുരം, കേരളത്തിൽ കൈകൊണ്ട് പാക്ക് ചെയ്യുന്നു • GST ബിൽ അഭ്യർത്ഥനയിൽ',
    checkout_address_title: 'ഡെലിവറി വിലാസം',
    checkout_payment_title: 'പേയ്‌മെന്റ് രീതി',
    checkout_payment_desc: 'ഓൺലൈൻ പേയ്‌മെന്റ് നീക്കം ചെയ്തു — ചെടികൾ ലഭിക്കുമ്പോൾ പണമടയ്ക്കുക.',
    checkout_cod_desc: 'ഡെലിവറിക്ക് ശേഷം പണമടയ്ക്കുക — ക്യാഷ് / UPI. മുൻകൂർ പണമടവ് ഇല്ല.',
    checkout_no_online: 'ഓൺലൈൻ പേയ്‌മെന്റ് ഇല്ല',
    checkout_gst: 'GST ബിൽ ലഭ്യം',
    checkout_how_it_works_text: 'ഓർഡർ നൽകുക → ഉടമയ്ക്ക് വാട്ട്‌സാപ്പ് അറിയിപ്പ് → ഉടമ മറുപടി → “നന്ദി” കാണാം → ഡെലിവറി + COD.',
    checkout_note_cuttings: 'കുറിപ്പ്: കട്ടിംഗ്സ് ഭാരം കുറവ് & സൗജന്യം. പോട്ടിന് ₹39-79 അധിക ഷിപ്പിംഗ് സ്ഥിരീകരണത്തിൽ ചേർക്കും.',
    checkout_inclusive: 'നികുതികൾ ഉൾപ്പെടെ • പോട്ടിന് അധിക ഷിപ്പിംഗ് ഉടമ വിളിച്ച് സ്ഥിരീകരിക്കും.',
    checkout_wholesale_discount: 'ഹോൾസെയിൽ അളവ് കിഴിവ് ബാധകം — കൂടുതൽ അളവ് = കുറഞ്ഞ വില.',
    checkout_by_placing: 'ഓർഡർ നൽകുമ്പോൾ ഉടമയ്ക്ക് വാട്ട്‌സാപ്പ് അറിയിപ്പ് ലഭിക്കും',
    checkout_safe: '🔒 COD സുരക്ഷിതം',
    checkout_replace: '↩️ 14ദി മാറ്റം',
    checkout_owner_call: '💬 ഉടമ വിളി',
    checkout_owner_mobile_title: 'ഉടമ മൊബൈൽ: +91 98765 43210',
    checkout_owner_mobile_desc: 'ഓർഡർ നൽകിയ ഉടൻ വാട്ട്‌സാപ്പിൽ അറിയിപ്പ് പോകുന്നു',
    checkout_please_login: 'ഓർഡർ ചരിത്രം സേവ് ചെയ്യാൻ ലോഗിൻ ചെയ്യുക.',
    checkout_login_link: 'ലോഗിൻ',
    checkout_edit_below: 'അല്ലെങ്കിൽ താഴെ സ്വമേധയാ എഡിറ്റ് ചെയ്യുക — ഡാഷ്‌ബോർഡിൽ സേവ് ചെയ്യാതെ പ്രൊഫൈൽ മാറില്ല.',
    checkout_potted_shipping: 'പോട്ടിന് ₹39-79 അധിക ഷിപ്പിംഗ് ഉടമ വിളിച്ച് സ്ഥിരീകരിക്കും.',
    checkout_total: 'ആകെ',
    checkout_shipping_label: 'ഷിപ്പിംഗ്',
    checkout_cod_label: 'COD',
    checkout_pay_on_delivery: 'ഡെലിവറിയിൽ പണമടയ്ക്കുക',
    checkout_placing: 'നൽകുന്നു...',
    dash_hello: 'ഹലോ',
    dash_green_family: 'നിങ്ങളുടെ ഹരിത കുടുംബത്തിൽ എന്താണ് സംഭവിക്കുന്നത്.',
    dash_download_all: 'എല്ലാ പരിചരണ ഗൈഡുകളും ഡൗൺലോഡ് ചെയ്യുക',
    dash_total_orders_label: 'മൊത്തം ഓർഡറുകൾ',
    dash_pending_label: 'തീർപ്പാക്കാത്തത്',
    dash_awaiting: 'സ്ഥിരീകരണം കാത്തിരിക്കുന്നു',
    dash_delivered_label: 'വിതരണം ചെയ്തു',
    dash_completed: 'പൂർത്തിയായി',
    dash_wishlist_label: 'വിഷ്‌ലിസ്റ്റ് ഇനങ്ങൾ',
    dash_saved: 'സേവ് ചെയ്തത്',
    dash_recent_orders: 'സമീപകാല ഓർഡറുകൾ',
    dash_view_all: 'എല്ലാം കാണുക →',
    dash_no_orders: 'ഇതുവരെ ഓർഡറുകളില്ല. നിങ്ങളുടെ ഹരിത കുടുംബം കാത്തിരിക്കുന്നു!',
    dash_browse_plants: 'ചെടികൾ ബ്രൗസ് ചെയ്യുക',
    dash_care_reminders_title: 'പരിചരണ ഓർമ്മപ്പെടുത്തലുകൾ',
    dash_no_plants: 'വ്യക്തിഗത പരിചരണ ഷെഡ്യൂൾ ലഭിക്കാൻ ചെടി വാങ്ങുക 🌿',
    dash_guide: 'ഗൈഡ്',
    dash_download_care_guides: 'പരിചരണ ഗൈഡുകൾ ഡൗൺലോഡ് ചെയ്യുക (PDF)',
    dash_seasonal: 'സീസണൽ ഓർമ്മപ്പെടുത്തലുകൾ 🍂',
    dash_check_drainage: 'ഡ്രെയിനേജ് പരിശോധിക്കുക — മൺസൂൺ തയ്യാറെടുപ്പ്',
    dash_mist: 'ഉഷ്ണമേഖലാ ചെടികൾ ആഴ്ചയിൽ 2 തവണ നനയ്ക്കുക',
    dash_next: 'അടുത്തത്:',
    dash_fertilize: 'വളമിടുക',
    dash_repot: '30 ദിവസത്തിനുള്ളിൽ റീപോട്ട് ചെയ്യുക',
    dash_subscribe: 'അലേർട്ടുകൾ സബ്‌സ്‌ക്രൈബ് ചെയ്യുക',
    dash_my_orders: 'എന്റെ ഓർഡറുകൾ',
    dash_track_reorder: 'ട്രാക്ക് ചെയ്യുക, വീണ്ടും ഓർഡർ ചെയ്യുക, ഇൻവോയ്സ് ഡൗൺലോഡ് ചെയ്യുക',
    dash_all: 'എല്ലാം',
    dash_shipped: 'ഷിപ്പ് ചെയ്തു',
    dash_cancelled: 'റദ്ദാക്കി',
    dash_view_details: 'വിശദാംശങ്ങൾ കാണുക →',
    dash_hide_details: 'വിശദാംശങ്ങൾ മറയ്ക്കുക',
    dash_no_orders_filter: 'ഇതിൽ ഓർഡറുകളില്ല',
    dash_itemized: 'ഇനം തിരിച്ച്',
    dash_reorder_btn: 'വീണ്ടും ഓർഡർ ചെയ്യുക',
    dash_download_invoice: 'ഇൻവോയ്സ് ഡൗൺലോഡ് ചെയ്യുക',
    dash_cancel_order: 'ഓർഡർ റദ്ദാക്കുക — കാരണം ആവശ്യം',
    dash_shipping_address: 'ഷിപ്പിംഗ് വിലാസം',
    dash_tracking: 'ട്രാക്കിംഗ് ടൈംലൈൻ',
    dash_order_placed_timeline: 'ഓർഡർ നൽകി',
    dash_confirmed_timeline: 'സ്ഥിരീകരിച്ചു',
    dash_shipped_timeline: 'ഷിപ്പ് ചെയ്തു',
    dash_delivered_timeline: 'വിതരണം ചെയ്തു',
    dash_cancelled_reason: 'റദ്ദാക്കി — കാരണം',
    dash_my_wishlist: 'എന്റെ വിഷ്‌ലിസ്റ്റ്',
    dash_saved_wishlist: 'സേവ് ചെയ്തത്',
    dash_browse_plants_wl: 'ചെടികൾ ബ്രൗസ് ചെയ്യുക →',
    dash_download_all_guides: 'എല്ലാ ഗൈഡുകളും ഡൗൺലോഡ് ചെയ്യുക',
    dash_wl_empty_title: 'വിഷ്‌ലിസ്റ്റ് ശൂന്യമാണ്',
    dash_wl_empty_desc: 'പിന്നീട് വാങ്ങാൻ പ്രിയപ്പെട്ടവ സേവ് ചെയ്യുക',
    dash_in_stock: 'സ്റ്റോക്കിൽ ഉണ്ട്',
    dash_out_stock: 'സ്റ്റോക്കില്ല',
    dash_move_cart: 'കാർട്ടിലേക്ക് മാറ്റുക',
    dash_remove: 'നീക്കം ചെയ്യുക',
    dash_notify_stock: 'സ്റ്റോക്കിൽ വന്നാൽ അറിയിക്കുക',
    dash_download_care: 'പരിചരണ ഗൈഡ് PDF ഡൗൺലോഡ് ചെയ്യുക',
    dash_saved_addresses: 'സേവ് ചെയ്ത വിലാസങ്ങൾ',
    dash_add_new: '+ പുതിയ വിലാസം ചേർക്കുക',
    dash_home: 'ഹോം',
    dash_work: 'ജോലി',
    dash_other: 'മറ്റ്',
    dash_use_current: 'നിലവിലെ ലൊക്കേഷൻ ഉപയോഗിക്കുക',
    dash_locating: 'കണ്ടെത്തുന്നു...',
    dash_street: 'തെരുവ് *',
    dash_city_input: 'നഗരം *',
    dash_state_input: 'സംസ്ഥാനം',
    dash_postal_input: 'പിൻ കോഡ്',
    dash_country_input: 'രാജ്യം',
    dash_set_default: 'സ്ഥിര വിലാസമായി സജ്ജമാക്കുക',
    dash_pin_preview: 'നഗരം പൂരിപ്പിച്ച ശേഷം പിൻ കാണാം • മാപ്പ് പ്രിവ്യൂ',
    dash_save: 'വിലാസം സേവ് ചെയ്യുക',
    dash_update: 'വിലാസം അപ്ഡേറ്റ് ചെയ്യുക',
    dash_cancel_btn: 'റദ്ദാക്കുക',
    dash_no_addresses: 'വിലാസങ്ങളില്ല. ചെക്ക്ഔട്ടിൽ ചേർത്തത് — അല്ലെങ്കിൽ മുകളിൽ ചേർക്കുക.',
    dash_default: 'സ്ഥിരം',
    dash_edit: 'എഡിറ്റ്',
    dash_delete: 'ഇല്ലാതാക്കുക',
    dash_set_as_default: 'സ്ഥിരമായി സജ്ജമാക്കുക',
    dash_profile_settings: 'പ്രൊഫൈൽ ക്രമീകരണങ്ങൾ',
    dash_click_avatar: 'അവതാർ മാറ്റാൻ ക്ലിക്ക് ചെയ്യുക • JPG/PNG പരമാവധി 2MB',
    dash_preview_ready: 'പ്രിവ്യൂ തയ്യാർ — സേവ് ചെയ്ത് പ്രയോഗിക്കുക',
    dash_full_name: 'പൂർണ്ണ പേര്',
    dash_phone_number: 'ഫോൺ നമ്പർ',
    dash_email: 'ഇമെയിൽ',
    dash_reverify: '(മാറ്റിയാൽ വീണ്ടും പരിശോധിക്കണം)',
    dash_email_changed: '⚠ ഇമെയിൽ മാറ്റി — സേവ് ചെയ്ത ശേഷം വീണ്ടും പരിശോധിക്കണം.',
    dash_notif_prefs: 'അറിയിപ്പ് മുൻഗണനകൾ',
    dash_order_updates: 'ഓർഡർ അപ്ഡേറ്റുകൾ (SMS/ഇമെയിൽ)',
    dash_order_updates_desc: 'ഷിപ്പിംഗ്, ഡെലിവറി, റദ്ദാക്കലുകൾ',
    dash_promo: 'പ്രമോഷനുകളും ഓഫറുകളും',
    dash_promo_desc: 'സീസണൽ കിഴിവുകൾ, പുതിയ വരവുകൾ',
    dash_care_emails: 'പരിചരണ ഇമെയിലുകൾ',
    dash_care_desc: 'വാരാന്ത നന & വള ടിപ്പുകൾ',
    dash_save_changes: 'മാറ്റങ്ങൾ സേവ് ചെയ്യുക',
    dash_change_password: 'പാസ്‌വേഡ് മാറ്റുക',
    dash_current_password: 'നിലവിലെ പാസ്‌വേഡ്',
    dash_new_password: 'പുതിയ പാസ്‌വേഡ്',
    dash_confirm_new: 'പുതിയത് സ്ഥിരീകരിക്കുക',
    dash_update_password: 'പാസ്‌വേഡ് അപ്ഡേറ്റ് ചെയ്യുക',
    dash_danger: 'അപകട മേഖല — അക്കൗണ്ട് ഇല്ലാതാക്കുക',
    dash_delete_desc: 'അക്കൗണ്ടും എല്ലാ ഡാറ്റയും ഇല്ലാതാക്കുക. ഇത് പഴയപടിയാക്കാനാവില്ല.',
    dash_delete_perm: 'അക്കൗണ്ട് ശാശ്വതമായി ഇല്ലാതാക്കുക',
    dash_support_history: 'പിന്തുണ ടിക്കറ്റ് ചരിത്രം',
    dash_new_query: 'പുതിയ ചോദ്യം — ഉദാ: ഡെലിവറി പ്രശ്നം...',
    dash_submit: 'സമർപ്പിക്കുക',
    dash_sidebar_profile: 'പ്രൊഫൈൽ',
    dash_sidebar_overview: 'അവലോകനം',
    dash_sidebar_orders: 'ഓർഡറുകൾ',
    dash_sidebar_wishlist: 'വിഷ്‌ലിസ്റ്റ്',
    dash_sidebar_addresses: 'വിലാസങ്ങൾ',
    dash_sidebar_profile_link: 'പ്രൊഫൈൽ',
    dash_continue_shopping: 'ഷോപ്പിംഗ് തുടരുക',
    dash_logout: 'ലോഗ്ഔട്ട്',
    dash_need_help_title: 'സഹായം വേണോ?',
    dash_need_help_desc: 'വാട്ട്‌സാപ്പിൽ ചെടി പരിചരണ ഉപദേശം നേടുക. സൗജന്യം.',
    dash_view_ticket: 'ടിക്കറ്റ് ചരിത്രം കാണുക',
    dash_profile_complete: 'പ്രൊഫൈൽ പൂർത്തിയായി!',
    dash_add_phone: 'ഫോൺ നമ്പർ ചേർക്കുക',
    dash_add_address: 'വിലാസം ചേർക്കുക',
    contact_badge: 'ബന്ധപ്പെടുക • 2 മണിക്കൂറിൽ മറുപടി',
    contact_hero_title1: 'നിങ്ങളിൽ നിന്ന് കേൾക്കാൻ',
    contact_hero_title2: 'ഞങ്ങൾ ആഗ്രഹിക്കുന്നു',
    contact_hero_desc: 'ചെടിയെക്കുറിച്ചുള്ള ചോദ്യം, ബൾക്ക് ഓർഡർ, അല്ലെങ്കിൽ ഹരിതഗൃഹ സന്ദർശനം? കർഷകർ 2 മണിക്കൂറിനുള്ളിൽ മറുപടി നൽകും (9am-7pm).',
    contact_phone_display: '📞 +91 98765 43210',
    contact_email_display: '✉ hello@greennest.com',
    contact_whatsapp_display: '💬 വാട്ട്‌സാപ്പ് ചെയ്യുക',
    contact_care_expert: 'മീര — പരിചരണ വിദഗ്ധ',
    contact_replies_in: 'സാധാരണ 18 മിനിറ്റിനുള്ളിൽ മറുപടി',
    contact_send_title: 'സന്ദേശം അയയ്ക്കുക',
    contact_send_desc: 'റീട്ടെയിൽ, ഹോൾസെയിൽ (10+), അല്ലെങ്കിൽ ഹരിതഗൃഹ സന്ദർശനത്തിന്. ഇമെയിൽ + വാട്ട്‌സാപ്പ് വഴി മറുപടി.',
    contact_sent_success: 'സന്ദേശം അയച്ചു! ഉടമയെ അറിയിച്ചു — ഉടൻ “നന്ദി” ലഭിക്കും.',
    contact_name_placeholder: 'പ്രിയ ശർമ്മ',
    contact_email_placeholder: 'you@email.com',
    contact_select_topic: 'വിഷയം തിരഞ്ഞെടുക്കുക',
    contact_retail: 'റീട്ടെയിൽ ഓർഡർ സഹായം',
    contact_wholesale: 'ഹോൾസെയിൽ / ബൾക്ക് (10+ )',
    contact_care_support: 'ചെടി പരിചരണ പിന്തുണ',
    contact_greenhouse_visit: 'ഹരിതഗൃഹ സന്ദർശനം',
    contact_other: 'മറ്റ്',
    contact_message_placeholder: 'ഹായ്, പേഴുംമൂട്, തിരുവനന്തപുരത്തുള്ള എന്റെ നഴ്‌സറിക്ക് 25 അലോവേര പോട്ടും 10 കട്ടിംഗും വേണം...',
    contact_send_btn: 'സന്ദേശം അയയ്ക്കുക →',
    contact_sending: 'അയയ്ക്കുന്നു...',
    contact_avg_reply: 'ശരാശരി മറുപടി 18 മിനിറ്റ് • തിങ്കൾ-ശനി 9am-7pm • ഉടമയുടെ മൊബൈലിൽ വാട്ട്‌സാപ്പ് അറിയിപ്പ്',
    contact_private: '🔒 സ്വകാര്യം',
    contact_no_spam: '✓ സ്പാം ഇല്ല',
    contact_whatsapp_badge: '💬 വാട്ട്‌സാപ്പ്',
    contact_visit_title: 'ഞങ്ങളുടെ ഹരിതഗൃഹം സന്ദർശിക്കുക',
    contact_greenhouse_name: 'ഗ്രീൻനെസ്റ്റ് നഴ്‌സറി, H34Q+9FP',
    contact_greenhouse_address: 'പൂവച്ചൽ, കേരളം 695575 • 2 ഏക്കർ ഓർഗാനിക് ഫാം ശനി 10am-4pm • സൗജന്യ ടൂറും പഠനവും',
    contact_call: '+91 98765 43210',
    contact_call_desc: 'വിളിക്കുക / വാട്ട്‌സാപ്പ് • തിങ്കൾ-ശനി 9am-7pm',
    contact_hello_email: 'hello@greennest.com',
    contact_hello_desc: 'ഹോൾസെയിൽ: bulk@greennest.com • GST ഇൻവോയ്സ്',
    contact_whatsapp_us: 'വാട്ട്‌സാപ്പിൽ ബന്ധപ്പെടുക →',
    contact_find_map: 'മാപ്പിൽ കണ്ടെത്തുക',
    contact_poovachal: 'പൂവച്ചൽ • 2022',
    contact_open_maps: 'മാപ്പിൽ തുറക്കുക →',
    contact_hours_title: 'പ്രവൃത്തി സമയം',
    contact_hours_desc: 'തിങ്കൾ-ശനി 9am-7pm • ഞായർ അടച്ചു • വാട്ട്‌സാപ്പ് 24മ (അടുത്ത പ്രവൃത്തി മണിക്കൂറിൽ മറുപടി)',
    contact_select_topic_label: 'വിഷയം തിരഞ്ഞെടുക്കുക',
    footer_brand_desc: '2015 മുതൽ നിങ്ങളുടെ വാതിൽപ്പടിയിൽ സന്തോഷം എത്തിക്കുന്ന ഇക്കോ ഫ്രണ്ട്‌ലി നഴ്‌സറി.',
    footer_quick_links: 'ദ്രുത ലിങ്കുകൾ',
    footer_shop_link: 'ഷോപ്പ്',
    footer_about_link: 'ഞങ്ങളെക്കുറിച്ച്',
    footer_contact_link: 'ബന്ധപ്പെടുക',
    footer_contact_title: 'ബന്ധപ്പെടുക',
    footer_contact_address: '123 ഗ്രീൻ ലെയ്ൻ, പേഴുംമൂട്, ടിവിഎം, ഇന്ത്യ +91 98765 43210 hello@greennest.com',
    footer_contact_address_line1: '123 ഗ്രീൻ ലെയ്ൻ, പേഴുംമൂട്, ടിവിഎം, ഇന്ത്യ',
    footer_phone: '+91 98765 43210',
    footer_email: 'hello@greennest.com',
    footer_newsletter: 'വാർത്താക്കുറിപ്പ്',
    footer_newsletter_placeholder: 'നിങ്ങളുടെ ഇമെയിൽ',
    footer_join: 'ചേരുക',
    footer_rights: '© 2026 ഗ്രീൻനെസ്റ്റ്. എല്ലാ അവകാശങ്ങളും സംരക്ഷിതം.',
    footer_subscribed: 'സബ്‌സ്‌ക്രൈബ് ചെയ്തു — ഇമെയിൽ പരിശോധിക്കുക',
    auth_welcome_back: 'വീണ്ടും സ്വാഗതം',
    auth_est: '2022 • 12k+ കുടുംബങ്ങൾ വിശ്വസിക്കുന്നു',
    auth_signin_desc: 'ഓർഡറുകൾ ട്രാക്ക് ചെയ്യാനും വിലാസങ്ങൾ നിയന്ത്രിക്കാനും പരിചരണ പിന്തുണ നേടാനും സൈൻ ഇൻ ചെയ്യുക. പുതിയ ആളാണോ?',
    auth_create_account: 'അക്കൗണ്ട് സൃഷ്ടിക്കുക',
    auth_email_address: 'ഇമെയിൽ വിലാസം',
    auth_password: 'പാസ്‌വേഡ്',
    auth_forgot: 'മറന്നോ?',
    auth_show: 'കാണിക്കുക',
    auth_hide: 'മറയ്ക്കുക',
    auth_keep_signed: 'സൈൻ ഇൻ നിലനിർത്തുക',
    auth_sign_in_continue: 'സൈൻ ഇൻ — തുടരുക →',
    auth_signing_in: 'സൈൻ ഇൻ ചെയ്യുന്നു...',
    auth_or: 'അല്ലെങ്കിൽ',
    auth_continue_google: 'Google ഉപയോഗിച്ച് തുടരുക',
    auth_demo: 'ഡെമോ:',
    auth_demo_customer: 'ഉപഭോക്താവ് → പുതിയത് രജിസ്റ്റർ ചെയ്യുക • അഡ്മിൻ →',
    auth_admin_creds: 'admin@greennest.com / admin123',
    auth_est_badge: '2022 • പേഴുംമൂട്, ടിവിഎം',
    auth_plants_thrive: 'വളരുന്ന ചെടികൾ',
    auth_actually_thrive: 'യഥാർത്ഥത്തിൽ നിലനിൽക്കുന്നു.',
    auth_plants_desc: '4 വർഷം, 50k ചെടികൾ, 12k കുടുംബങ്ങൾ. ആദ്യം മുതൽ ഓർഗാനിക്, ക്രഷ്-പ്രൂഫ് ട്യൂബുകളിൽ വിതരണം.',
    auth_quote_name: 'റിയ • 2023 ഉപഭോക്താവ്',
    auth_quote: '“എന്റെ അലോ 2 വർഷത്തിനു ശേഷവും നന്നായി വളരുന്നു!”',
    auth_join_us: 'ഞങ്ങളോടൊപ്പം ചേരുക',
    auth_join_year: '2022',
    auth_get_off: '10% കിഴിവ് + സൗജന്യ പരിചരണ ഗൈഡ്. 4 വർഷം, 12k കുടുംബങ്ങൾ.',
    auth_account: 'അക്കൗണ്ട്',
    auth_address: 'വിലാസം',
    auth_full_name: 'പൂർണ്ണ പേര്',
    auth_phone: 'ഫോൺ',
    auth_email: 'ഇമെയിൽ',
    auth_confirm: 'സ്ഥിരീകരിക്കുക',
    auth_strength: 'ശക്തി',
    auth_continue_address: 'വിലാസത്തിലേക്ക് തുടരുക →',
    auth_have_account: 'അക്കൗണ്ട് ഉണ്ടോ?',
    auth_sign_in: 'സൈൻ ഇൻ ചെയ്യുക',
    auth_where_deliver: 'എവിടെ വിതരണം ചെയ്യണം?',
    auth_use_location: 'ലൊക്കേഷൻ ഉപയോഗിക്കുക',
    auth_street_house: 'തെരുവ്, വീട് നമ്പർ',
    auth_city: 'നഗരം',
    auth_state: 'സംസ്ഥാനം',
    auth_postal: 'പിൻ കോഡ്',
    auth_country: 'രാജ്യം',
    auth_terms: 'ഞാൻ നിബന്ധനകളും സ്വകാര്യതയും അംഗീകരിക്കുന്നു. 2022 ഗ്രീൻനെസ്റ്റ്.',
    auth_back: 'മടങ്ങുക',
    auth_create_account_btn: 'അക്കൗണ്ട് സൃഷ്ടിക്കുക →',
    auth_creating: 'സൃഷ്ടിക്കുന്നു...',
    auth_your_journey: 'നിങ്ങളുടെ ചെടി',
    auth_journey_span: 'യാത്ര ഇവിടെ തുടങ്ങുന്നു.',
    auth_since_desc: '2022 മുതൽ, 12k കുടുംബങ്ങളെ വീട് പച്ചപ്പാക്കാൻ സഹായിച്ചു. ഓർഗാനിക്, സത്യസന്ധം, ജീവിതകാല പിന്തുണ.',
    auth_perks: 'ആനുകൂല്യങ്ങൾ',
    auth_off_first: 'ആദ്യ ഓർഡറിന് 10% കിഴിവ്',
    auth_track_orders: 'ഓർഡറുകളും സേവുകളും ട്രാക്ക് ചെയ്യുക',
    auth_whatsapp_care: 'വാട്ട്‌സാപ്പ് പരിചരണ പിന്തുണ',
  }
};

const Ctx = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(()=> localStorage.getItem('lang') || 'en');
  useEffect(()=> localStorage.setItem('lang', lang), [lang]);
  useEffect(()=>{ document.documentElement.lang = lang; },[lang]);
  const t = (key) => translations[lang]?.[key] || translations.en[key] || key;
  const toggle = () => setLang(l=> l==='en' ? 'ml' : 'en');
  return <Ctx.Provider value={{ lang, setLang, t, toggle, translations }}>{children}</Ctx.Provider>;
}
export const useLanguage = () => useContext(Ctx);
