// Simple in-memory fallback when Supabase not configured - for demo/dev (expanded schema)
export const db = {
  users: [
    {
      id: "admin-1",
      name: "Admin",
      email: "mohammedashiqueofficial7@gmail.com",
      password_hash:
        "$2a$10$y8mRl10UDywQnyPvp0kUYOltUKDdk2/8Zn1/x7Lr6/hBYMiYGR6BS",
      phone: "+1234567890",
      role: "admin",
      email_verified: true,
      created_at: new Date().toISOString(),
    },
  ],
  categories: [
    {
      id: "1",
      name: "Indoor Plants",
      description: "Perfect for interiors • Air purifying",
    },
    { id: "2", name: "Outdoor Plants", description: "Garden favorites" },
    { id: "3", name: "Succulents", description: "Low maintenance • Medicinal" },
    { id: "4", name: "Flowering Plants", description: "Colorful blooms" },
    { id: "5", name: "Seeds & Tools", description: "Grow yourself" },
  ],
  plants: [
    {
      id: "p1",
      name: "Aloe Vera",
      botanical_name: "Aloe barbadensis miller",
      botanical: "Aloe barbadensis miller",
      category_id: "3",
      sku: "GN-ALOE-001",
      price: 180,
      wholesale_price: 129,
      market_price: 299,
      discount_price: 229,
      stock_qty: 85,
      stock_status: "in_stock",
      short_description:
        "Medicinal succulent — gel-filled leaves, air-purifying, low-maintenance.",
      long_description:
        "Aloe Vera is a hardy succulent prized for its thick gel-filled leaves used for burns, skincare and air purification. This Indian-origin perennial thrives indoors or on balconies, produces pups for propagation, and needs minimal care. Ships as 3-inch bareroot or 5-inch potted.",
      sunlight: "Bright",
      watering_frequency: "Water when top 2 inches dry (7-10 days)",
      soil_type: "Well-draining sandy or cactus mix, pH 6.0-7.0",
      temperature_range: "18-30°C",
      humidity_preference: "Low to medium (30-50%)",
      fertilizer_schedule: "Cactus fertilizer every 2 months, spring-summer",
      pet_safe: false,
      growth_rate: "medium",
      mature_size: "30-40 cm height, 20 cm spread",
      difficulty_level: "easy",
      pot_included: true,
      pot_size: "5 inch (12 cm) plastic, optional ceramic",
      height_at_shipping: "12-15 cm",
      weight: "400-600 g (potted)",
      wholesale_note: "Wholesale: min 25 pcs @ ₹129. Retail: ₹249 (MRP ₹299).",
      shipping_extra:
        "Extra shipping ₹49 for potted (soil weight). Cuttings ship free over ₹399.",
      cuttings_available: true,
      potted_available: true,
      care_instructions:
        "Bright indirect to full sun, water when soil dries, well-draining sandy mix. Harvest gel after 8 months.",
      rating: 4.8,
      type: "Potted",
      care_level: "easy",
      origin: "India",
      images: ["/aloevera plant.png", "/aloevera plant.png"],
      variants: [
        {
          id: "plastic-pot",
          label: "With Plastic Pot",
          priceMin: 180,
          priceMax: 180,
        },
        {
          id: "cutting",
          label: "Cutting/Offset",
          priceMin: 20,
          priceMax: 20,
          disabled: true,
          note: "cutting not available",
        },
        {
          id: "cutting-cover",
          label: "Cutting + Plastic Cover",
          priceMin: 150,
          priceMax: 150,
        },
      ],
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: "p2",
      name: "Calathea Plant",
      botanical_name: "Goeppertia ornata",
      botanical: "Calathea ornata / Goeppertia",
      category_id: "1",
      sku: "GN-CAL-002",
      price: 180,
      wholesale_price: 249,
      market_price: 649,
      discount_price: 399,
      stock_qty: 34,
      stock_status: "in_stock",
      short_description:
        "Premium prayer plant with large striped foliage — tropical showstopper.",
      long_description:
        "Calathea (Prayer Plant) is a tropical interior gem known for large green leaves with cream stripes that move with light. Native to South American rainforests, it loves humidity and bright indirect light, ideal for living rooms. Ships in 12-18 cm pot with well-drained mix.",
      sunlight: "Indirect",
      watering_frequency: "Keep soil moist (2-3 days), mist leaves",
      soil_type: "Well-drained peat + perlite, pH 5.5-6.5",
      temperature_range: "18-27°C",
      humidity_preference: "High (60-80%)",
      fertilizer_schedule: "Liquid fertilizer monthly, spring-autumn",
      pet_safe: true,
      growth_rate: "medium",
      mature_size: "40-50 cm height",
      difficulty_level: "medium",
      pot_included: true,
      pot_size: "12-18 cm nursery pot",
      height_at_shipping: "20-30 cm",
      weight: "500-700 g",
      wholesale_note:
        "Wholesale: min 10 pcs @ ₹249 (market ₹649). Retail: ₹449.",
      shipping_extra:
        "Potted only — extra shipping ₹79 due to large foliage (hand-packed).",
      cuttings_available: false,
      potted_available: true,
      care_instructions:
        "Bright indirect light, keep soil moist not soggy, high humidity 60%+, avoid direct sun, well-drained.",
      rating: 4.7,
      type: "Potted",
      care_level: "medium",
      origin: "India",
      images: ["/calathea plant.jpg", "/red calathea.jpg"],
      variants: [
        {
          id: "plastic-pot",
          label: "With Plastic Pot",
          priceMin: 180,
          priceMax: 180,
        },
        {
          id: "cutting",
          label: "Cutting/Division",
          priceMin: 40,
          priceMax: 40,
        },
        {
          id: "cutting-cover",
          label: "Cutting + Plastic Cover",
          priceMin: 50,
          priceMax: 50,
        },
      ],
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: "p3",
      name: "Chinese Evergreen (Aglaonema)",
      botanical_name: "Aglaonema commutatum Snow White",
      botanical: "Aglaonema commutatum Snow White",
      category_id: "1",
      sku: "GN-AGLA-003",
      price: 150,
      wholesale_price: 179,
      market_price: 465,
      discount_price: 259,
      stock_qty: 48,
      stock_status: "in_stock",
      short_description:
        "Air-purifying indoor plant with elegant white-patterned foliage.",
      long_description:
        "Aglaonema Chinese Evergreen Snow White brings calm white-green variegation to any room. Air-purifying, low-effort, premium self-watering 5″ pot, perfect for beginners and offices. Indian climate ready, USDA friendly.",
      sunlight: "Indirect",
      watering_frequency: "Weekly, allow top inch to dry",
      soil_type: "Rich coco-peat + compost, well-drained",
      temperature_range: "16-30°C",
      humidity_preference: "Medium (40-60%)",
      fertilizer_schedule: "Every 2 months, spring-summer",
      pet_safe: false,
      growth_rate: "medium",
      mature_size: "25-35 cm height, 30 cm spread",
      difficulty_level: "easy",
      pot_included: true,
      pot_size: "5 inch premium self-watering",
      height_at_shipping: "18-25 cm",
      weight: "450 g",
      wholesale_note:
        "Wholesale: min 20 pcs @ ₹179 (MRP ₹465). Retail: ₹299. Bulk 4+ @ ₹249 each.",
      shipping_extra:
        "Cuttings: free ship. Potted (5″ premium pot): extra ₹49 shipping.",
      cuttings_available: true,
      potted_available: true,
      care_instructions:
        "Bright indirect light, water weekly, low maintenance, well-drained coco-peat mix.",
      rating: 4.6,
      type: "Potted",
      care_level: "easy",
      origin: "India",
      images: ["/chinese evergreen.png"],
      variants: [
        {
          id: "plastic-pot",
          label: "With Plastic Pot",
          priceMin: 150,
          priceMax: 150,
        },
        {
          id: "cutting",
          label: "Cutting/Division",
          priceMin: 100,
          priceMax: 100,
        },
        {
          id: "cutting-cover",
          label: "Cutting + Plastic Cover",
          priceMin: 120,
          priceMax: 120,
        },
      ],
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: "p4",
      name: "Patharchatta (Bryophyllum) — Paathi Pull",
      botanical_name: "Bryophyllum pinnatum",
      botanical: "Bryophyllum pinnatum / Kalanchoe pinnata",
      category_id: "3",
      sku: "GN-PATH-004",
      price: 60,
      wholesale_price: 99,
      market_price: 349,
      discount_price: 149,
      stock_qty: 62,
      stock_status: "in_stock",
      short_description:
        "Miracle leaf — Ayurvedic medicinal succulent for kidney health & wounds.",
      long_description:
        "Patharchatta (Paathi Pull), also called Life Plant / Miracle Leaf, is a succulent native to Madagascar, widely used in Ayurveda for kidney stones, wound healing and hypertension. Fleshy cylindrical stem, 1m tall at maturity, produces plantlets on leaf margins. Includes care guide.",
      sunlight: "Full",
      watering_frequency: "Moderate (5-7 days), drought tolerant",
      soil_type: "Well-draining sandy loam, pH 6-7",
      temperature_range: "15-35°C",
      humidity_preference: "Low to medium (30-60%)",
      fertilizer_schedule: "Compost yearly, no frequent feed",
      pet_safe: false,
      growth_rate: "fast",
      mature_size: "60-100 cm",
      difficulty_level: "easy",
      pot_included: true,
      pot_size: "4 inch nursery pot",
      height_at_shipping: "10-15 cm",
      weight: "250 g (cutting 80 g)",
      wholesale_note:
        "Wholesale: min 30 pcs @ ₹99 (market ₹349). Retail: ₹199.",
      shipping_extra:
        "Cuttings ship free. Potted: extra ₹39 (soil). Pan-India 3-5 days.",
      cuttings_available: true,
      potted_available: true,
      care_instructions:
        "Full sun to partial shade, moderate water, drought tolerant, well-draining. Harvest leaves after 3 months.",
      rating: 4.5,
      type: "Potted / Cutting",
      care_level: "easy",
      origin: "India",
      images: ["/paathi pull.jpg"],
      variants: [
        {
          id: "plastic-pot",
          label: "With Plastic Pot",
          priceMin: 60,
          priceMax: 60,
        },
        { id: "cutting", label: "Cutting/Leaf", priceMin: 20, priceMax: 20 },
        {
          id: "cutting-cover",
          label: "Cutting + Plastic Cover",
          priceMin: 30,
          priceMax: 30,
        },
      ],
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: "p5",
      productId: "lucky-bamboo",
      name: "Lucky Bamboo (Dracaena sanderiana) — 2 Layer",
      botanical_name: "Dracaena sanderiana",
      botanical: "Dracaena sanderiana",
      category_id: "1",
      sku: "GN-LUCK-005",
      price: 150,
      wholesale_price: 112,
      market_price: 549,
      discount_price: 349,
      stock_qty: 110,
      stock_status: "in_stock",
      short_description:
        "Feng Shui 2-layer prosperity arrangement — grows in water, gift-ready.",
      long_description:
        "Lucky Bamboo 2-Layer is a Dracaena, not true bamboo, symbolizing happiness and wealth. 2-layer spiral arrangement, thrives in water or soil, bright indirect light, weekly water change. Popular for homes, offices, hotels and corporate gifting. Vase optional. 3-layer also available.",
      sunlight: "Indirect",
      watering_frequency: "Change water weekly, keep roots submerged",
      soil_type: "Water or well-draining potting mix",
      temperature_range: "18-35°C",
      humidity_preference: "Medium (40-70%)",
      fertilizer_schedule: "Liquid fertilizer monthly (few drops in water)",
      pet_safe: false,
      growth_rate: "slow",
      mature_size: "30-45 cm (2-layer)",
      difficulty_level: "easy",
      pot_included: true,
      pot_size: "Glass vase 4 inch / plastic pot optional",
      height_at_shipping: "25-30 cm",
      weight: "300 g (without water)",
      wholesale_note:
        "Wholesale: min 250 pcs @ ₹112.50 (retail ₹399-549, 3-layer ₹549).",
      shipping_extra:
        "Cuttings: ₹0. Potted with water vase: extra ₹60 fragile shipping. Bulk corporate gifting available.",
      cuttings_available: true,
      potted_available: true,
      care_instructions:
        "Bright indirect light, change water weekly, keep roots submerged, avoid direct sun.",
      rating: 4.9,
      type: "Potted / Water",
      care_level: "easy",
      origin: "India",
      images: ["/lucky bamboo.jpg"],
      variants: [
        {
          id: "plastic-pot",
          label: "With Plastic Pot",
          priceMin: 150,
          priceMax: 150,
        },
        { id: "cutting", label: "Cutting", priceMin: 50, priceMax: 50 },
        {
          id: "cutting-cover",
          label: "Cutting + Plastic Cover",
          priceMin: 95,
          priceMax: 95,
        },
      ],
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: "p6",
      name: "Areca Palm (Dypsis lutescens)",
      botanical_name: "Dypsis lutescens",
      botanical: "Dypsis lutescens",
      category_id: "1",
      sku: "GN-AREC-006",
      price: 180,
      wholesale_price: 199,
      market_price: 550,
      discount_price: 349,
      stock_qty: 27,
      stock_status: "low_stock",
      short_description:
        "Feathery air-purifying palm — tropical, fast-growing, elegant.",
      long_description:
        "Areca Palm, native to Madagascar, brings feathery arching fronds and lush tropical feel. Excellent air purifier removing formaldehyde and xylene. Adapts to various light, thrives in warm humid indoor environments. Ships as 12 cm starter or 10″ pot, nursery-mature.",
      sunlight: "Bright",
      watering_frequency: "Keep soil moist, water when top inch dry (3-4 days)",
      soil_type: "Well-draining loamy with perlite, pH 6-6.5",
      temperature_range: "18-30°C",
      humidity_preference: "High (50-70%) mist occasionally",
      fertilizer_schedule: "Monthly spring-summer, balanced fertilizer",
      pet_safe: true,
      growth_rate: "fast",
      mature_size: "150-200 cm indoor",
      difficulty_level: "medium",
      pot_included: true,
      pot_size: "10 inch pot / 12 cm starter",
      height_at_shipping: "30-40 cm (12 cm pot) / 60 cm (10″)",
      weight: "800 g (12 cm) / 2 kg (10″)",
      wholesale_note:
        "Wholesale: min 15 pcs @ ₹199 (MRP ₹550). Retail: ₹399 (was ₹479 at Nurserylive).",
      shipping_extra:
        "Large palm: extra shipping ₹79-99 due to height (packed in tube). Store pickup available Pezhummoodu, Thiruvananthapuram, Kerala (H34Q+9FP, Poovachal) • 2-acre nursery.",
      cuttings_available: false,
      potted_available: true,
      care_instructions:
        "Bright indirect light, moderate water, humid, well-drained, fertilize spring.",
      rating: 4.7,
      type: "Potted",
      care_level: "medium",
      origin: "India",
      images: ["/palm.jpg"],
      variants: [
        {
          id: "plastic-pot",
          label: "With Plastic Pot",
          priceMin: 180,
          priceMax: 180,
        },
        {
          id: "cutting",
          label: "Cutting/Division",
          priceMin: 130,
          priceMax: 130,
        },
        {
          id: "cutting-cover",
          label: "Cutting + Plastic Cover",
          priceMin: 150,
          priceMax: 150,
        },
      ],
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
    {
      id: "p7",
      name: "Red Calathea (Roseopicta)",
      botanical_name: "Calathea roseopicta",
      botanical: "Calathea roseopicta",
      category_id: "1",
      sku: "GN-RCAL-007",
      price: 200,
      wholesale_price: 299,
      market_price: 899,
      discount_price: 599,
      stock_qty: 19,
      stock_status: "low_stock",
      short_description:
        "Rare burgundy-green patterned leaves — premium indoor showstopper.",
      long_description:
        "Red Calathea Roseopicta features large green-black leaves with bright pink-red strokes and cream patterns. Prayer plant that moves with light, premium 12 cm to 7-inch ceramic options. Demands high humidity and distilled water, rewarding with striking foliage.",
      sunlight: "Indirect",
      watering_frequency: "Keep moist, 2-3 days, high humidity",
      soil_type: "Peat-based, well-drained, pH 5.5-6",
      temperature_range: "18-27°C",
      humidity_preference: "High (65-85%)",
      fertilizer_schedule: "Monthly spring-autumn, half-strength",
      pet_safe: true,
      growth_rate: "medium",
      mature_size: "40-50 cm",
      difficulty_level: "medium",
      pot_included: true,
      pot_size: "12 cm nursery / 7 inch ceramic",
      height_at_shipping: "18-25 cm",
      weight: "600 g",
      wholesale_note:
        "Wholesale: min 10 pcs @ ₹299 (market ₹899). Retail: ₹649 (Chhajed ₹599-899).",
      shipping_extra:
        "Potted only: extra ₹79 boxed. Cuttings not viable for this cultivar.",
      cuttings_available: false,
      potted_available: true,
      care_instructions:
        "Bright indirect, high humidity, distilled water preferred, keep soil moist, no direct sun.",
      rating: 4.8,
      type: "Potted",
      care_level: "medium",
      origin: "India",
      images: ["/red calathea.jpg", "/calathea plant.jpg"],
      variants: [
        {
          id: "plastic-pot",
          label: "With Plastic Pot",
          priceMin: 200,
          priceMax: 200,
        },
        {
          id: "cutting",
          label: "Cutting/Division",
          priceMin: 130,
          priceMax: 130,
        },
        {
          id: "cutting-cover",
          label: "Cutting + Plastic Cover",
          priceMin: 170,
          priceMax: 170,
        },
      ],
      created_at: new Date().toISOString(),
      updated_at: new Date().toISOString(),
    },
  ],
  plant_images: [
    {
      id: "pi1",
      plant_id: "p1",
      image_url: "/aloevera plant.png",
      display_order: 0,
    },
    {
      id: "pi1b",
      plant_id: "p1",
      image_url: "/aloevera plant.png",
      display_order: 1,
    },
    {
      id: "pi2",
      plant_id: "p2",
      image_url: "/calathea plant.jpg",
      display_order: 0,
    },
    {
      id: "pi2b",
      plant_id: "p2",
      image_url: "/red calathea.jpg",
      display_order: 1,
    },
    {
      id: "pi3",
      plant_id: "p3",
      image_url: "/chinese evergreen.png",
      display_order: 0,
    },
    {
      id: "pi4",
      plant_id: "p4",
      image_url: "/paathi pull.jpg",
      display_order: 0,
    },
    {
      id: "pi5",
      plant_id: "p5",
      image_url: "/lucky bamboo.jpg",
      display_order: 0,
    },
    { id: "pi6", plant_id: "p6", image_url: "/palm.jpg", display_order: 0 },
    {
      id: "pi7",
      plant_id: "p7",
      image_url: "/red calathea.jpg",
      display_order: 0,
    },
    {
      id: "pi7b",
      plant_id: "p7",
      image_url: "/calathea plant.jpg",
      display_order: 1,
    },
  ],
  plant_reviews: [
    {
      id: "1",
      plant_id: "p1",
      user_id: "u1",
      user_name: "Sarah J.",
      rating: 5,
      comment: "Aloe came with pups! Super healthy, great packaging.",
      review_image_url: null,
      created_at: new Date().toISOString(),
    },
    {
      id: "2",
      plant_id: "p5",
      user_id: "u2",
      user_name: "Amit R.",
      rating: 5,
      comment: "Lucky bamboo 2-layer packaging top class, gifted to office.",
      review_image_url: null,
      created_at: new Date().toISOString(),
    },
  ],
  // legacy aliases for compatibility
  get reviews() {
    return this.plant_reviews;
  },
  set reviews(v) {
    this.plant_reviews = v;
  },
  orders: [],
  cart_items: [],
  contact_messages: [],
  wishlist: [],
  addresses: [],
  login_logs: [],
};
export const genId = () => Math.random().toString(36).slice(2, 9);
export const genOrderId = () => {
  const d = new Date();
  const dd = String(d.getDate()).padStart(2, "0");
  const mm = String(d.getMonth() + 1).padStart(2, "0");
  const yyyy = d.getFullYear();
  const suffix = Math.random().toString(36).slice(2, 6).toUpperCase();
  return `ORD-${dd}-${mm}-${yyyy}-${suffix}`;
};
